from __future__ import annotations

import base64
import json
import logging
import threading
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List
from urllib import error as url_error
from urllib import request as url_request

import cv2
from google.genai import types
from PIL import Image

from src_llm.keyframes import Keyframe
from src_llm.llama_prereq import LlamaPrereqError, assert_llama_accessible

@dataclass
class SuggestedAction:
    type: str  # tap | scroll | type_text | press_back | press_home | wait | done
    target_description: str = ""
    resource_id: str | None = None
    coordinates: list[int] | None = None  # [x, y]
    text: str | None = None


@dataclass
class ScreenDescription:
    current_screen: str
    visible_elements: list[str]
    suggested_action: SuggestedAction
    reasoning: str
    confidence: float


@dataclass
class ExecutableAction:
    type: str  # tap | scroll | type_text | press_back | press_home | wait | done
    resource_id: str | None = None
    coordinates: list[int] | None = None  # [x, y]
    text: str | None = None
    direction: str | None = None  # for scroll: up|down|left|right
    target_description: str = ""


@dataclass
class ActionDecision:
    continue_automation: bool
    action: ExecutableAction | None
    reasoning: str
    confidence: float
    raw_response: str = ""


@dataclass(frozen=True)
class ProviderAction:
    screen_description: str
    action_type: str
    target: str
    details: str
    confidence: float
    timestamp_sec: float = 0.0


class ProviderError(RuntimeError):
    """Raised for provider-specific connectivity or inference failures."""


class BaseLLMProvider(ABC):
    """Common abstraction for open/closed model adapters."""

    def __init__(
        self,
        llm_name: str,
        llm_model: str,
        env: Dict[str, str],
        logger: logging.Logger,
    ) -> None:
        self.llm_name = llm_name
        self.llm_model = llm_model
        self.env = env
        self.logger = logger
        self.raw_llm_response: str | None = None
        # Each entry: {"kind": str, "elapsed_sec": float, "prompt_tokens": int, "output_tokens": int}
        self.llm_calls: list[dict] = []

    @abstractmethod
    def infer_actions(self, keyframes: List[Keyframe]) -> List[ProviderAction]:
        """Infer action hypotheses from selected keyframes."""

    def infer_memory_from_video(self, video_path: Path) -> str:
        """Analyze video and return structured markdown memory.

        Markdown format (for video_mode):
        # Task Summary
        [description of task]

        ## Steps
        1. Step 1 description
        2. Step 2 description
        ...

        ## UI Elements
        - Element 1: description
        - Element 2: description
        ...

        ## Completion Criteria
        - Criterion 1
        - Criterion 2
        ...
        """
        raise NotImplementedError(
            f"Provider '{self.llm_name}' does not support infer_memory_from_video(). "
            "Only 'gemini' is currently supported."
        )

    def infer_actions_from_video(self, video_path: Path) -> List[ProviderAction]:
        """Infer actions directly from a video file (video mode). Override in subclasses."""
        raise NotImplementedError(
            f"Provider '{self.llm_name}' does not support video_mode. "
            "Only 'gemini' is currently supported."
        )

    def validate_connection(self) -> None:
        """Optional provider preflight hook."""
        return None

    def _deterministic_fallback(self, keyframes: List[Keyframe], source: str) -> List[ProviderAction]:
        actions: List[ProviderAction] = []
        for idx, kf in enumerate(keyframes):
            if idx == 0:
                action_type = "launch_app"
                target = "app_entrypoint"
                details = f"{source}: initial frame likely app launch or resumed state"
                confidence = 0.88
            elif kf.motion_score >= 18:
                action_type = "tap"
                target = f"ui_element_step_{idx}"
                details = f"{source}: high visual transition suggests a click/tap action"
                confidence = 0.74
            elif kf.motion_score >= 9:
                action_type = "scroll"
                target = "scrollable_view"
                details = f"{source}: medium transition suggests scrolling/swiping"
                confidence = 0.66
            else:
                action_type = "wait"
                target = "current_screen"
                details = f"{source}: minimal transition indicates waiting or subtle input"
                confidence = 0.58

            desc = (
                f"Frame at {kf.timestamp_sec:.2f}s with motion_score={kf.motion_score:.2f}; "
                f"heuristic interpretation generated by {source}."
            )
            actions.append(
                ProviderAction(
                    screen_description=desc,
                    action_type=action_type,
                    target=target,
                    details=details,
                    confidence=confidence,
                )
            )
        return actions


class GeminiProvider(BaseLLMProvider):
    # Class-level singleton for genai.Client, keyed by resolved API key/auth mode
    _genai_client_instance: Any = None
    _genai_client_key: str | None = None
    _genai_client_lock: threading.Lock = threading.Lock()

    def validate_connection(self) -> None:
        self.logger.info(
            "Gemini preflight started | model=%s | validating API key and endpoint access",
            self.llm_model,
        )
        text, usage = self._generate(
            contents=["Reply with exactly: OK"],
            timeout_sec=30,
            request_kind="preflight",
        )
        self.logger.info("Gemini preflight successful | model=%s", self.llm_model)

    def _gemini_api_key(self) -> str:
        """Get Gemini API key from env, checking GEMINI_API_KEY first, then fallback."""
        key = str(self.env.get("GEMINI_API_KEY", "")).strip()
        if key:
            return key
        return str(self.env.get("GOOGLE_GENERATIVE_AI_API_KEY", "")).strip()

    def _gemini_vertex_project_id(self) -> str | None:
        """Get Vertex AI project ID from env, checking runtime override first, then ADC default."""
        project_id = str(self.env.get("GEMINI_VERTEX_PROJECT_ID", "")).strip()
        if project_id:
            return project_id
        try:
            _, adc_project = self._build_default_adc_token()
            return adc_project
        except ProviderError:
            return None

    def _gemini_vertex_location(self) -> str:
        """Get Vertex AI location from env, default to us-central1."""
        location = str(self.env.get("GEMINI_VERTEX_LOCATION", "")).strip()
        return location or "us-central1"

    def _genai_client(self) -> Any:
        """Get or create singleton genai.Client, thread-safe, cached by resolved key/auth mode."""
        try:
            from google import genai
        except ImportError as exc:
            raise ProviderError(
                "Gemini support requires the google-genai package. "
                "Install dependencies from src_llm/requirements.txt"
            ) from exc

        api_key = self._gemini_api_key()
        # Determine cache key: either API key or "adc" for ADC auth mode
        cache_key = api_key if api_key else "adc"

        with GeminiProvider._genai_client_lock:
            # Return cached client if key matches
            if (
                GeminiProvider._genai_client_instance is not None
                and GeminiProvider._genai_client_key == cache_key
            ):
                return GeminiProvider._genai_client_instance

            # Create new client based on auth mode
            if api_key:
                self.logger.debug("Creating genai.Client with API key")
                client = genai.Client(api_key=api_key)
            else:
                # ADC/Vertex AI mode
                project_id = self._gemini_vertex_project_id()
                location = self._gemini_vertex_location()
                if not project_id:
                    raise ProviderError(
                        "No project_id available for Vertex AI. "
                        "Set GEMINI_VERTEX_PROJECT_ID or configure Application Default Credentials."
                    )
                self.logger.debug(
                    "Creating genai.Client with Vertex AI | project=%s | location=%s",
                    project_id, location,
                )
                client = genai.Client(
                    api_key=None,
                    vertexai=True,
                    project=project_id,
                    location=location,
                )

            # Cache the new client
            GeminiProvider._genai_client_instance = client
            GeminiProvider._genai_client_key = cache_key
            return client

    def _generate(
        self,
        contents: list,
        timeout_sec: int,
        request_kind: str,
    ) -> tuple[str, dict]:
        """Call genai.Client.models.generate_content with retry logic for 429/timeout.

        Returns (response_text, usage_dict) where usage_dict contains token counts.
        Wraps SDK exceptions into ProviderError. Reimplements 429/timeout retry with
        exponential backoff (10/20/40/80/160s, 5 attempts).
        """
        client = self._genai_client()
        max_retries = 5
        base_delay = 10.0

        for attempt in range(max_retries + 1):
            try:
                self.logger.info(
                    "Gemini generateContent call | kind=%s | model=%s | attempt=%d/%d",
                    request_kind, self.llm_model, attempt + 1, max_retries + 1,
                )
                start = time.perf_counter()
                response = client.models.generate_content(
                    model=self.llm_model,
                    contents=contents,
                    config=types.GenerateContentConfig(temperature=0.1)
                )
                elapsed = time.perf_counter() - start
                self.logger.info(
                    "Gemini generateContent response | kind=%s | elapsed_sec=%.2f",
                    request_kind, elapsed,
                )

                # Extract response text and usage
                response_text = response.text.strip() if response.text else ""
                usage_dict = {
                    "prompt_token_count": getattr(response.usage_metadata, "prompt_token_count", 0),
                    "candidates_token_count": getattr(
                        response.usage_metadata, "candidates_token_count", 0
                    ),
                }

                return response_text, usage_dict

            except Exception as exc:
                error_name = type(exc).__name__
                error_msg = str(exc)
                is_rate_limit = "429" in error_msg or "quota" in error_msg.lower()
                is_timeout = isinstance(exc, TimeoutError) or "timeout" in error_msg.lower()

                if (is_rate_limit or is_timeout) and attempt < max_retries:
                    delay = base_delay * (2 ** attempt)
                    retry_type = "rate limit" if is_rate_limit else "timeout"
                    self.logger.warning(
                        "Gemini %s on attempt %d/%d — retrying in %.0fs | error=%s",
                        retry_type, attempt + 1, max_retries, delay, error_msg[:100],
                    )
                    time.sleep(delay)
                    continue

                # Non-retryable error
                raise ProviderError(
                    f"Gemini {request_kind} failed ({error_name}): {error_msg[:300]}"
                ) from exc

        raise ProviderError(f"Gemini {request_kind} exhausted {max_retries + 1} retry attempts")

    def infer_actions(self, keyframes: List[Keyframe]) -> List[ProviderAction]:
        if not keyframes:
            return []

        self.logger.info(
            "Sending Gemini inference request | model=%s | keyframes=%d",
            self.llm_model,
            len(keyframes),
        )
        prompt = self._build_action_prompt(keyframes)
        try:
            raw_text, usage = self._generate(
                contents=[prompt],
                timeout_sec=90,
                request_kind="action_inference",
            )
            self._record_call("action_inference", 0.0, usage)
            parsed = self._parse_actions(raw_text, keyframes)
            if parsed:
                self.logger.info(
                    "Gemini inference parsed successfully | parsed_actions=%d",
                    len(parsed),
                )
                return parsed
            self.logger.warning(
                "Gemini response could not be parsed into actions; falling back to deterministic heuristic."
            )
        except ProviderError as exc:
            self.logger.warning(
                "Gemini inference request failed (%s); falling back to deterministic heuristic.",
                exc,
            )

        return self._deterministic_fallback(keyframes, source="gemini_fallback")

    def describe_screen(
        self,
        screenshot_path: Path,
        accessibility_tree_xml: str | None = None,
    ) -> ScreenDescription:
        """Send a screenshot (and optionally accessibility tree) to Gemini and return structured screen description."""
        import xml.etree.ElementTree as ET

        # Build clickable elements summary from XML (avoid dumping raw verbose XML)
        clickable_summary = ""
        if accessibility_tree_xml:
            try:
                tree = ET.fromstring(accessibility_tree_xml)
                clickable = [
                    n for n in tree.findall(".//*")
                    if n.get("clickable") == "true"
                ][:20]
                lines = []
                for el in clickable:
                    rid = el.get("resource-id", "")
                    text = el.get("text", "")
                    bounds = el.get("bounds", "")
                    lines.append(f"  resource-id={rid!r} text={text!r} bounds={bounds}")
                if lines:
                    clickable_summary = "\n\nClickable UI elements from accessibility tree:\n" + "\n".join(lines)
            except ET.ParseError:
                pass

        prompt = (
            "You are an Android UI automation assistant. "
            "Look at this screenshot of an Android screen and return ONLY a JSON object with these keys:\n"
            '  "current_screen": short description of what screen/state is shown,\n'
            '  "visible_elements": array of visible UI element descriptions,\n'
            '  "suggested_action": object with keys:\n'
            '    "type": one of tap|scroll|type_text|press_back|press_home|wait|done,\n'
            '    "target_description": natural language description of target,\n'
            '    "resource_id": resource-id string or null,\n'
            '    "coordinates": [x, y] pixel coordinates or null,\n'
            '    "text": text to type if type_text else null,\n'
            '  "reasoning": why this action is the logical next step,\n'
            '  "confidence": float 0.0-1.0\n'
            "Return ONLY valid JSON, no markdown fences."
            + clickable_summary
        )

        # Load screenshot as PIL Image
        screenshot_image = Image.open(screenshot_path)

        self.logger.info("describe_screen: sending screenshot to Gemini | model=%s", self.llm_model)
        raw_text, usage = self._generate(
            contents=[prompt, screenshot_image],
            timeout_sec=180,
            request_kind="describe_screen",
        )
        self._record_call("describe_screen", 0.0, usage)

        return self._parse_screen_description(raw_text)

    def _parse_screen_description(self, raw_text: str) -> ScreenDescription:
        text = raw_text.strip()
        # Strip markdown fences if present
        if "```" in text:
            for chunk in text.split("```"):
                cleaned = chunk.strip()
                if cleaned.startswith("json"):
                    cleaned = cleaned[4:].strip()
                if cleaned.startswith("{"):
                    text = cleaned
                    break
        try:
            obj = json.loads(text)
        except json.JSONDecodeError as exc:
            raise ProviderError(f"describe_screen: could not parse JSON: {exc}\nRaw: {text[:300]}") from exc

        action_raw = obj.get("suggested_action", {}) or {}
        coords = action_raw.get("coordinates")
        if coords and isinstance(coords, list) and len(coords) == 2:
            try:
                coords = [int(coords[0]), int(coords[1])]
            except (TypeError, ValueError):
                coords = None
        else:
            coords = None

        suggested = SuggestedAction(
            type=str(action_raw.get("type", "wait")).strip() or "wait",
            target_description=str(action_raw.get("target_description", "")).strip(),
            resource_id=action_raw.get("resource_id") or None,
            coordinates=coords,
            text=action_raw.get("text") or None,
        )

        confidence_raw = obj.get("confidence", 0.5)
        try:
            confidence = float(confidence_raw)
        except (TypeError, ValueError):
            confidence = 0.5

        return ScreenDescription(
            current_screen=str(obj.get("current_screen", "")).strip(),
            visible_elements=list(obj.get("visible_elements", [])),
            suggested_action=suggested,
            reasoning=str(obj.get("reasoning", "")).strip(),
            confidence=max(0.0, min(1.0, confidence)),
        )

    def decide_next_action(
        self,
        history: list,
        screenshot: "PIL.Image.Image",
        accessibility_tree: str | None,
        task_description: str = "",
    ) -> "ActionDecision":
        """Given history of turns and current screenshot, decide the next action.

        Returns an ActionDecision with continue_automation flag and action details.
        """
        import xml.etree.ElementTree as ET

        # Build clickable elements summary
        clickable_summary = ""
        if accessibility_tree:
            try:
                tree = ET.fromstring(accessibility_tree)
                clickable = [
                    n for n in tree.findall(".//*")
                    if n.get("clickable") == "true"
                ][:20]
                lines = []
                for el in clickable:
                    rid = el.get("resource-id", "")
                    text = el.get("text", "")
                    bounds = el.get("bounds", "")
                    lines.append(f"  resource-id={rid!r} text={text!r} bounds={bounds}")
                if lines:
                    clickable_summary = "\n\nClickable UI elements:\n" + "\n".join(lines)
            except ET.ParseError:
                pass

        # Build history summary
        history_text = ""
        if history:
            steps = []
            for turn in history:
                action_desc = "initial state"
                if turn.action_taken:
                    a = turn.action_taken
                    action_desc = f"{a.type}"
                    if a.resource_id:
                        action_desc += f" on {a.resource_id}"
                    elif a.coordinates:
                        action_desc += f" at {a.coordinates}"
                steps.append(f"  Step {turn.step_index + 1}: {action_desc}")
            history_text = "\n\nPrevious steps taken:\n" + "\n".join(steps)

        task_line = f"\nTask: {task_description}" if task_description else ""

        prompt = (
            "You are an Android UI automation assistant driving a live device.{task_line}\n"
            "Look at the current screenshot and decide the next action.\n"
            "IMPORTANT: If you have taken the same action 3 or more consecutive times and the "
            "screen has not changed, set \"continue\": false — the task has either completed or "
            "cannot proceed further.\n"
            "Return ONLY a JSON object with these keys:\n"
            '  "continue": true if more actions are needed, false if task is complete or stuck,\n'
            '  "action": object with keys:\n'
            '    "type": one of tap|scroll|type_text|press_back|press_home|wait|done,\n'
            '    "resource_id": resource-id string or null,\n'
            '    "coordinates": [x, y] pixel coordinates or null,\n'
            '    "text": text string for type_text else null,\n'
            '    "direction": up|down|left|right for scroll else null,\n'
            '    "target_description": natural language description of target,\n'
            '  "reasoning": why this is the right next action,\n'
            '  "confidence": float 0.0-1.0\n'
            "If continue=false, action can be null.\n"
            "Return ONLY valid JSON, no markdown fences."
        ).format(task_line=task_line) + history_text + clickable_summary

        self.logger.info("decide_next_action: calling Gemini | model=%s", self.llm_model)
        raw_text, usage = self._generate(
            contents=[prompt, screenshot],
            timeout_sec=180,
            request_kind="decide_next_action",
        )
        self._record_call("decide_next_action", 0.0, usage)
        return self._parse_action_decision(raw_text)

    def _parse_action_decision(self, raw_text: str) -> "ActionDecision":
        text = raw_text.strip()
        if "```" in text:
            for chunk in text.split("```"):
                cleaned = chunk.strip()
                if cleaned.startswith("json"):
                    cleaned = cleaned[4:].strip()
                if cleaned.startswith("{"):
                    text = cleaned
                    break
        try:
            obj = json.loads(text)
        except json.JSONDecodeError as exc:
            raise ProviderError(f"decide_next_action: could not parse JSON: {exc}\nRaw: {text[:300]}") from exc

        continue_auto = bool(obj.get("continue", True))
        reasoning = str(obj.get("reasoning", "")).strip()
        confidence_raw = obj.get("confidence", 0.5)
        try:
            confidence = float(confidence_raw)
        except (TypeError, ValueError):
            confidence = 0.5

        action_raw = obj.get("action") or {}
        if not action_raw or not continue_auto:
            action = None
        else:
            coords = action_raw.get("coordinates")
            if coords and isinstance(coords, list) and len(coords) == 2:
                try:
                    coords = [int(coords[0]), int(coords[1])]
                except (TypeError, ValueError):
                    coords = None
            else:
                coords = None
            action = ExecutableAction(
                type=str(action_raw.get("type", "wait")).strip() or "wait",
                resource_id=action_raw.get("resource_id") or None,
                coordinates=coords,
                text=action_raw.get("text") or None,
                direction=action_raw.get("direction") or None,
                target_description=str(action_raw.get("target_description", "")).strip(),
            )

        return ActionDecision(
            continue_automation=continue_auto,
            action=action,
            reasoning=reasoning,
            confidence=max(0.0, min(1.0, confidence)),
            raw_response=raw_text,
        )

    def summarize_video_task(self, keyframes: List["Keyframe"]) -> str:
        """Send keyframes to Gemini and get a plain-text summary of the task shown in the video.

        Used as the initial context for the automation loop so the LLM knows
        what it is trying to reproduce on the live device.
        """
        if not keyframes:
            return ""

        # Build multipart contents: interleave images with timestamp captions
        contents: list = []
        for idx, kf in enumerate(keyframes):
            # Convert keyframe BGR (cv2 format) to RGB PIL Image
            rgb_array = cv2.cvtColor(kf.image_bgr, cv2.COLOR_BGR2RGB)
            pil_image = Image.fromarray(rgb_array)
            contents.append(pil_image)
            contents.append(f"Frame {idx + 1} at {kf.timestamp_sec:.1f}s")

        contents.append(
            "These are keyframes from a screen recording of an Android app.\n"
            "Describe in 2-4 sentences what task the user is performing in the video. "
            "Be specific about the sequence of actions (e.g. 'The user opens AdAway, "
            "grants root permission by tapping Allow, then enables host blocking.'). "
            "Return only the plain-text description, no JSON."
        )

        self.logger.info(
            "summarize_video_task: sending %d keyframes to Gemini | model=%s",
            len(keyframes), self.llm_model,
        )
        raw_text, usage = self._generate(
            contents=contents,
            timeout_sec=120,
            request_kind="summarize_video_task",
        )
        self._record_call("summarize_video_task", 0.0, usage)
        return raw_text.strip()

    def summarize_video_task_from_video(self, video_path: "Path") -> str:
        """Summarize the task shown in a raw video file without keyframe extraction.

        Uses the same task-description prompt as ``summarize_video_task`` but
        sends the full video inline via ``_send_video_request``, allowing Gemini
        to reason over temporal motion rather than still frames.

        Raises ``ProviderError`` on any failure so callers can fall back to the
        keyframe pipeline.
        """
        prompt_text = (
            "This is a screen recording of an Android app.\n"
            "Describe in 2-4 sentences what task the user is performing in the video. "
            "Be specific about the sequence of actions (e.g. 'The user opens AdAway, "
            "grants root permission by tapping Allow, then enables host blocking.'). "
            "Return only the plain-text description, no JSON."
        )
        self.logger.info(
            "summarize_video_task_from_video: sending raw video to Gemini | video=%s",
            video_path.name,
        )
        raw_text, usage = self._send_video_request(video_path, prompt_text)
        self._record_call("summarize_video_task_from_video", 0.0, usage)
        return raw_text.strip()

    def decide_next_action_with_video_context(
        self,
        history: list,
        screenshot: "PIL.Image.Image",
        accessibility_tree: str | None,
        task_description: str,
        video_summary: str,
    ) -> "ActionDecision":
        """Like decide_next_action but includes the video task summary as additional context."""
        import xml.etree.ElementTree as ET

        # Build clickable elements summary
        clickable_summary = ""
        if accessibility_tree:
            try:
                tree = ET.fromstring(accessibility_tree)
                clickable = [
                    n for n in tree.findall(".//*")
                    if n.get("clickable") == "true"
                ][:20]
                lines = []
                for el in clickable:
                    rid = el.get("resource-id", "")
                    text_val = el.get("text", "")
                    bounds = el.get("bounds", "")
                    lines.append(f"  resource-id={rid!r} text={text_val!r} bounds={bounds}")
                if lines:
                    clickable_summary = "\n\nClickable UI elements:\n" + "\n".join(lines)
            except ET.ParseError:
                pass

        # Build history summary
        history_text = ""
        if history:
            steps = []
            for turn in history:
                action_desc = "initial state"
                if turn.action_taken:
                    a = turn.action_taken
                    action_desc = f"{a.type}"
                    if a.resource_id:
                        action_desc += f" on {a.resource_id}"
                    elif a.coordinates:
                        action_desc += f" at {a.coordinates}"
                steps.append(f"  Step {turn.step_index + 1}: {action_desc}")
            history_text = "\n\nPrevious steps taken:\n" + "\n".join(steps)

        prompt = (
            "You are an Android UI automation assistant. "
            f"You are trying to reproduce the following task on a live device:\n\n"
            f"TASK: {task_description}\n\n"
            f"VIDEO SUMMARY: {video_summary}\n\n"
            "Look at the current screenshot and decide the next action to reproduce the task.\n"
            "IMPORTANT: If you have taken the same action 3 or more consecutive times and the "
            "screen has not changed, set \"continue\": false — the task has either completed or "
            "cannot proceed further. Do not keep scrolling indefinitely.\n"
            "Return ONLY a JSON object with these keys:\n"
            '  "continue": true if more actions are needed, false if task is complete or stuck,\n'
            '  "action": object with keys:\n'
            '    "type": one of tap|scroll|type_text|press_back|press_home|wait|done,\n'
            '    "resource_id": resource-id string or null,\n'
            '    "coordinates": [x, y] pixel coordinates or null,\n'
            '    "text": text string for type_text else null,\n'
            '    "direction": up|down|left|right for scroll else null,\n'
            '    "target_description": natural language description of target,\n'
            '  "reasoning": why this is the right next action,\n'
            '  "confidence": float 0.0-1.0\n'
            "If continue=false, action can be null.\n"
            "Return ONLY valid JSON, no markdown fences."
        ) + history_text + clickable_summary

        self.logger.debug("LLM Prompt (first 500 chars): %s", prompt[:500])

        self.logger.info("decide_next_action_with_video_context: calling Gemini | model=%s", self.llm_model)
        raw_text, usage = self._generate(
            contents=[prompt, screenshot],
            timeout_sec=180,
            request_kind="decide_next_action_with_video_context",
        )
        self.logger.debug("LLM raw response: %s", raw_text)
        self._record_call("decide_next_action_with_video_context", 0.0, usage)
        self.logger.info("LLM extracted text: %s", raw_text)

        decision = self._parse_action_decision(raw_text)
        self.logger.info("Parsed decision | continue=%s action=%s | raw_json=%s",
                         decision.continue_automation,
                         decision.action.type if decision.action else "none",
                         raw_text)
        return decision

    def _record_call(self, kind: str, elapsed: float, data: dict) -> None:
        """Append per-call stats to llm_calls using SDK usage dict or legacy usageMetadata."""
        # Support both new SDK format (direct dict with snake_case keys)
        # and legacy format (REST response with usageMetadata camelCase)
        if "prompt_token_count" in data:
            # SDK format
            prompt_tokens = int(data.get("prompt_token_count") or 0)
            output_tokens = int(data.get("candidates_token_count") or 0)
        else:
            # Legacy REST format
            usage = data.get("usageMetadata") or {}
            prompt_tokens = int(usage.get("promptTokenCount") or 0)
            output_tokens = int(usage.get("candidatesTokenCount") or 0)

        self.llm_calls.append({
            "kind": kind,
            "elapsed_sec": elapsed,
            "prompt_tokens": prompt_tokens,
            "output_tokens": output_tokens,
        })

    def _build_action_prompt(self, keyframes: List[Keyframe]) -> str:
        keyframe_lines = [
            (
                f"- idx={idx + 1}, timestamp_sec={frame.timestamp_sec:.3f}, "
                f"motion_score={frame.motion_score:.3f}"
            )
            for idx, frame in enumerate(keyframes)
        ]
        joined = "\n".join(keyframe_lines)
        return (
            "You are inferring a mobile bug reproduction trace from frame metadata.\n"
            "Return ONLY valid JSON as an array, one object per keyframe, with keys:\n"
            "screen_description, action_type, target, details, confidence.\n"
            "confidence must be between 0 and 1.\n"
            "Keyframes:\n"
            f"{joined}\n"
        )

    def _build_default_adc_token(self) -> tuple[str, str | None]:
        try:
            import google.auth
            from google.auth.transport.requests import Request
        except ImportError as exc:
            raise ProviderError(
                "google-auth is required for ADC auth. "
                "Install dependencies from src_llm/requirements.txt"
            ) from exc

        try:
            creds, project_id = google.auth.default(
                scopes=["https://www.googleapis.com/auth/cloud-platform"]
            )
            creds.refresh(Request())
        except Exception as exc:
            raise ProviderError(
                "Failed to load Application Default Credentials via google.auth.default(). "
                "Set GOOGLE_APPLICATION_CREDENTIALS, run gcloud auth application-default login, "
                "or provide GEMINI_API_KEY or GOOGLE_GENERATIVE_AI_API_KEY."
            ) from exc

        token = getattr(creds, "token", None)
        if not token:
            raise ProviderError("ADC token refresh returned empty token")
        return token, project_id

    def _parse_actions(
        self,
        raw_text: str,
        keyframes: List[Keyframe],
    ) -> List[ProviderAction] | None:
        text = raw_text.strip()
        if "```" in text:
            chunks = text.split("```")
            for chunk in chunks:
                cleaned = chunk.strip()
                if cleaned.startswith("json"):
                    cleaned = cleaned[4:].strip()
                if cleaned.startswith("["):
                    text = cleaned
                    break
        if not text.startswith("["):
            return None

        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            return None
        if not isinstance(parsed, list):
            return None

        actions: List[ProviderAction] = []
        for idx, item in enumerate(parsed):
            if idx >= len(keyframes):
                break
            if not isinstance(item, dict):
                return None
            screen_description = str(item.get("screen_description", "")).strip()
            action_type = str(item.get("action_type", "")).strip()
            target = str(item.get("target", "")).strip()
            details = str(item.get("details", "")).strip()
            confidence_raw = item.get("confidence", 0.5)
            try:
                confidence = float(confidence_raw)
            except (TypeError, ValueError):
                confidence = 0.5

            if not action_type:
                return None
            actions.append(
                ProviderAction(
                    screen_description=screen_description
                    or f"Gemini-inferred state for keyframe {idx + 1}",
                    action_type=action_type,
                    target=target or f"ui_target_{idx + 1}",
                    details=details or "No additional details provided by Gemini.",
                    confidence=max(0.0, min(1.0, confidence)),
                )
            )

        if not actions:
            return None
        while len(actions) < len(keyframes):
            fallback = self._deterministic_fallback(
                [keyframes[len(actions)]], source="gemini_partial_fallback"
            )[0]
            actions.append(fallback)
        return actions


class GeminiVideoProvider(GeminiProvider):
    """Gemini provider that sends an entire video file inline to Vertex AI generateContent."""

    def __init__(
        self,
        llm_name: str,
        llm_model: str,
        env: Dict[str, str],
        logger: logging.Logger,
        llm_prompt_file: Path | None = None,
    ) -> None:
        super().__init__(llm_name, llm_model, env, logger)
        self._llm_prompt_file = llm_prompt_file

    def _send_video_request(self, video_path: Path, prompt_text: str) -> tuple[str, dict]:
        """Load video file, send to Gemini via SDK, return (response_text, usage_dict)."""
        try:
            from google import genai
        except ImportError as exc:
            raise ProviderError(
                "Gemini video support requires the google-genai package. "
                "Install dependencies from src_llm/requirements.txt"
            ) from exc

        file_size = video_path.stat().st_size
        self.logger.info(
            "Loading video for upload | file=%s | size=%d bytes",
            video_path.name, file_size,
        )
        with video_path.open("rb") as f:
            video_bytes = f.read()

        self.logger.info(
            "Sending video inference request | model=%s | video=%s",
            self.llm_model, video_path.name,
        )

        video_mime_types = {
            ".mp4": "video/mp4",
            ".mov": "video/quicktime",
            ".avi": "video/x-msvideo",
            ".mkv": "video/x-matroska",
            ".webm": "video/webm",
            ".m4v": "video/x-m4v",
        }
        mime_type = video_mime_types.get(video_path.suffix.lower(), "video/mp4")

        # Create video part using SDK
        video_part = genai.types.Part.from_bytes(
            data=video_bytes,
            mime_type=mime_type,
        )

        # Call _generate with video part and prompt
        raw_text, usage = self._generate(
            contents=[prompt_text, video_part],
            timeout_sec=300,
            request_kind="video_inference",
        )

        self.raw_llm_response = raw_text
        return raw_text, usage

    def infer_memory_from_video(self, video_path: Path) -> str:
        """Send video to Gemini with the memory prompt, return raw Markdown text."""
        default_memory_prompt = Path("src_llm/input/prompts/llama_action_prompt_memory.txt")
        prompt_path = self._llm_prompt_file or default_memory_prompt
        try:
            prompt_text = prompt_path.read_text(encoding="utf-8")
        except OSError as exc:
            raise ProviderError(f"Failed to read memory prompt: {prompt_path}") from exc

        raw_text, usage = self._send_video_request(video_path, prompt_text)
        self._record_call("infer_memory_from_video", 0.0, usage)
        return raw_text

    def infer_actions_from_video(self, video_path: Path) -> List[ProviderAction]:
        """Send video to Gemini, parse actions from response."""
        default_prompt = Path("src_llm/input/prompts/gemini_video_prompt.txt")
        prompt_path = self._llm_prompt_file or default_prompt
        try:
            prompt_text = prompt_path.read_text(encoding="utf-8")
        except OSError as exc:
            raise ProviderError(f"Failed to read video prompt: {prompt_path}") from exc

        raw_text, usage = self._send_video_request(video_path, prompt_text)
        self._record_call("infer_actions_from_video", 0.0, usage)

        actions = self._parse_video_actions(raw_text)
        if not actions:
            raise ProviderError("Video mode: response could not be parsed into actions")
        self.logger.info("Video inference parsed | actions=%d", len(actions))
        return actions

    def _parse_video_actions(self, raw_text: str) -> List[ProviderAction] | None:
        """Parse JSON array from video mode response (no keyframe count constraint)."""
        text = raw_text.strip()
        if "```" in text:
            for chunk in text.split("```"):
                cleaned = chunk.strip()
                if cleaned.startswith("json"):
                    cleaned = cleaned[4:].strip()
                if cleaned.startswith("["):
                    text = cleaned
                    break
        if not text.startswith("["):
            return None
        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            return None
        if not isinstance(parsed, list) or not parsed:
            return None

        actions: List[ProviderAction] = []
        for item in parsed:
            if not isinstance(item, dict):
                continue
            action_type = str(item.get("action_type", "")).strip()
            if not action_type:
                continue
            confidence_raw = item.get("confidence", 0.5)
            try:
                confidence = float(confidence_raw)
            except (TypeError, ValueError):
                confidence = 0.5
            ts_raw = item.get("timestamp_sec", 0.0)
            try:
                timestamp_sec = float(ts_raw)
            except (TypeError, ValueError):
                timestamp_sec = 0.0
            actions.append(ProviderAction(
                screen_description=str(item.get("screen_description", "")).strip() or "video frame",
                action_type=action_type,
                target=str(item.get("target", "")).strip() or "unknown",
                details=str(item.get("details", "")).strip(),
                confidence=max(0.0, min(1.0, confidence)),
                timestamp_sec=timestamp_sec,
            ))
        return actions or None


class SonnetProvider(BaseLLMProvider):
    def infer_actions(self, keyframes: List[Keyframe]) -> List[ProviderAction]:
        # TODO: Integrate Anthropic Claude/Sonnet image+text API invocation.
        self.logger.warning(
            "Sonnet provider running in stub mode (TODO API integration). model=%s",
            self.llm_model,
        )
        return self._deterministic_fallback(keyframes, source="sonnet_stub")


class LlamaProvider(BaseLLMProvider):
    def __init__(
        self,
        llm_name: str,
        llm_model: str,
        env: Dict[str, str],
        logger: logging.Logger,
        action_prompt_path: Path,
    ) -> None:
        super().__init__(llm_name, llm_model, env, logger)
        self.action_prompt_path = action_prompt_path

    def validate_connection(self) -> None:
        try:
            assert_llama_accessible(
                base_url=str(self.env.get("LLAMA_BASE_URL", "")),
                model=self.llm_model,
                api_key=str(self.env.get("LLAMA_API_KEY", "")),
                timeout_sec=30,
            )
        except LlamaPrereqError as exc:
            raise ProviderError(str(exc)) from exc

    def infer_actions(self, keyframes: List[Keyframe]) -> List[ProviderAction]:
        if not keyframes:
            return []

        self.logger.info(
            "Sending Llama inference request | model=%s | keyframes=%d",
            self.llm_model,
            len(keyframes),
        )
        prompt = self._build_action_prompt(keyframes)
        raw_timeout = str(self.env.get("LLAMA_TIMEOUT_SEC", "")).strip()
        timeout_sec: int | None = None
        if raw_timeout:
            try:
                parsed = int(raw_timeout)
                timeout_sec = parsed if parsed > 0 else None
            except ValueError:
                pass
        self.logger.info(
            "Llama inference timeout | timeout_sec=%s",
            timeout_sec if timeout_sec is not None else "unlimited",
        )
        try:
            raw_text = self._call_llama(
                prompt=prompt,
                keyframes=keyframes,
                timeout_sec=timeout_sec,
                request_kind="action_inference",
            )
            self.raw_llm_response = raw_text
            parsed = self._parse_actions(raw_text, keyframes)
            if parsed:
                self.logger.info(
                    "Llama inference parsed successfully | parsed_actions=%d",
                    len(parsed),
                )
                return parsed
            self.logger.warning(
                "Llama response could not be parsed into actions; falling back to deterministic heuristic."
            )
        except ProviderError as exc:
            self.logger.warning(
                "Llama inference request failed (%s); falling back to deterministic heuristic.",
                exc,
            )

        return self._deterministic_fallback(keyframes, source="llama_fallback")

    def _build_action_prompt(self, keyframes: List[Keyframe]) -> str:
        keyframe_lines = [
            (
                f"- idx={idx + 1}, timestamp_sec={frame.timestamp_sec:.3f}, "
                f"motion_score={frame.motion_score:.3f}"
            )
            for idx, frame in enumerate(keyframes)
        ]
        joined = "\n".join(keyframe_lines)
        try:
            template = self.action_prompt_path.read_text(encoding="utf-8")
        except OSError as exc:
            raise ProviderError(
                f"Failed to read llm_prompt_file: {self.action_prompt_path}"
            ) from exc

        if "{KEYFRAMES}" in template:
            return template.replace("{KEYFRAMES}", joined)
        if "{keyframes}" in template:
            return template.replace("{keyframes}", joined)
        if not template.endswith("\n"):
            template += "\n"
        return f"{template}\nKeyframes to analyse:\n{joined}\n"

    def _call_llama(
        self,
        prompt: str,
        keyframes: List[Keyframe] | None,
        timeout_sec: int | None,
        request_kind: str,
    ) -> str:
        base_url = str(self.env.get("LLAMA_BASE_URL", "")).strip()
        if not base_url:
            raise ProviderError("Missing LLAMA_BASE_URL for llama provider.")

        normalized_base = base_url.rstrip("/")
        if normalized_base.endswith("/v1/chat/completions"):
            url = normalized_base
        elif normalized_base.endswith("/v1"):
            url = f"{normalized_base}/chat/completions"
        else:
            url = f"{normalized_base}/v1/chat/completions"

        headers = {"Content-Type": "application/json"}
        api_key = str(self.env.get("LLAMA_API_KEY", "")).strip()
        if api_key:
            headers["Authorization"] = f"Bearer {api_key}"

        payload: Dict[str, Any] = {
            "model": self.llm_model,
            "temperature": 0.1,
            "repeat_penalty": 1.3,
            "stream": True,
        }
        if self._supports_vision() and keyframes:
            payload["messages"] = [
                {
                    "role": "user",
                    "content": self._build_multimodal_content(prompt, keyframes),
                }
            ]
        else:
            payload["messages"] = [{"role": "user", "content": prompt}]

        payload_bytes = json.dumps(payload).encode("utf-8")
        req = url_request.Request(
            url=url,
            data=payload_bytes,
            headers=headers,
            method="POST",
        )

        self.logger.info(
            "Llama API request sent | kind=%s | model=%s | endpoint=%s | waiting for response",
            request_kind,
            self.llm_model,
            url,
        )
        start = time.perf_counter()

        # Heartbeat: log every 2 min while waiting so the log shows the model is still working
        heartbeat_stop = threading.Event()
        def _heartbeat() -> None:
            interval = 120
            elapsed_hb = 0
            while not heartbeat_stop.wait(timeout=interval):
                elapsed_hb += interval
                self.logger.info(
                    "Llama still processing | kind=%s | elapsed_sec=%d | tokens_so_far=%d",
                    request_kind,
                    elapsed_hb,
                    len(accumulated_tokens),
                )
        accumulated_tokens: List[str] = []
        hb_thread = threading.Thread(target=_heartbeat, daemon=True)
        hb_thread.start()

        try:
            with url_request.urlopen(req, timeout=timeout_sec) as response:
                for raw_line in response:
                    line = raw_line.decode("utf-8").strip()
                    if not line:
                        continue
                    # Strip SSE "data: " prefix if present
                    if line.startswith("data:"):
                        line = line[len("data:"):].strip()
                    if line in ("[DONE]", ""):
                        continue
                    try:
                        chunk = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    delta = ""
                    choices = chunk.get("choices")
                    if isinstance(choices, list) and choices:
                        delta = str(choices[0].get("delta", {}).get("content") or "")
                    if delta:
                        accumulated_tokens.append(delta)
                        self.logger.debug("Llama token chunk | chars=%d | content=%r", len(delta), delta[:80])
        except url_error.HTTPError as exc:
            heartbeat_stop.set()
            err_body = exc.read().decode("utf-8", errors="replace")
            raise ProviderError(
                f"Llama HTTP error {exc.code} during {request_kind}: {err_body[:300]}"
            ) from exc
        except url_error.URLError as exc:
            heartbeat_stop.set()
            raise ProviderError(f"Llama URL error during {request_kind}: {exc}") from exc
        except TimeoutError as exc:
            heartbeat_stop.set()
            partial = "".join(accumulated_tokens)
            self.logger.warning(
                "Llama request timed out during %s after %ss | partial_chars=%d | partial_preview=%r",
                request_kind,
                timeout_sec,
                len(partial),
                partial[:200],
            )
            raise ProviderError(
                f"Llama request timed out during {request_kind} after {timeout_sec}s"
            ) from exc
        finally:
            heartbeat_stop.set()

        elapsed = time.perf_counter() - start
        full_text = "".join(accumulated_tokens)
        self.logger.info(
            "Llama API response complete | kind=%s | elapsed_sec=%.2f | total_chars=%d",
            request_kind,
            elapsed,
            len(full_text),
        )
        return full_text

    def _parse_actions(
        self,
        raw_text: str,
        keyframes: List[Keyframe],
    ) -> List[ProviderAction] | None:
        text = raw_text.strip()
        if "```" in text:
            chunks = text.split("```")
            for chunk in chunks:
                cleaned = chunk.strip()
                if cleaned.startswith("json"):
                    cleaned = cleaned[4:].strip()
                if cleaned.startswith("["):
                    text = cleaned
                    break
        if not text.startswith("["):
            bracket_idx = text.find("\n[")
            if bracket_idx != -1:
                text = text[bracket_idx:].strip()
            else:
                return None

        # Strip any trailing prose after the JSON array (e.g. "Note: ..." lines)
        bracket_end = text.rfind("]")
        if bracket_end != -1:
            text = text[: bracket_end + 1]

        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            return None
        if not isinstance(parsed, list):
            return None

        actions: List[ProviderAction] = []
        for idx, item in enumerate(parsed):
            if idx >= len(keyframes):
                break
            if not isinstance(item, dict):
                return None
            screen_description = str(item.get("screen_description", "")).strip()
            action_type = self._normalize_action_type(str(item.get("action_type", "")).strip())
            target = str(item.get("target", "")).strip()
            details = str(item.get("details", "")).strip()
            confidence_raw = item.get("confidence", 0.5)
            try:
                confidence = float(confidence_raw)
            except (TypeError, ValueError):
                confidence = 0.5

            if not action_type:
                return None
            if self._is_placeholder_text(screen_description):
                return None
            if self._is_placeholder_text(details):
                return None
            if self._is_placeholder_text(target) and action_type != "launch":
                return None
            actions.append(
                ProviderAction(
                    screen_description=screen_description
                    or f"Llama-inferred state for keyframe {idx + 1}",
                    action_type=action_type,
                    target=target or f"ui_target_{idx + 1}",
                    details=details or "No additional details provided by Llama.",
                    confidence=max(0.0, min(1.0, confidence)),
                )
            )

        if not actions:
            return None
        while len(actions) < len(keyframes):
            fallback = self._deterministic_fallback(
                [keyframes[len(actions)]], source="llama_partial_fallback"
            )[0]
            actions.append(fallback)
        return actions

    def _supports_vision(self) -> bool:
        model = self.llm_model.lower()
        _VISION_MARKERS = ("vision", "vl", "llava", "minicpm-v", "minicpmv", "gemma3", "gemma-3")
        return any(m in model for m in _VISION_MARKERS)

    def _build_multimodal_content(
        self,
        prompt: str,
        keyframes: List[Keyframe],
    ) -> List[Dict[str, Any]]:
        content: List[Dict[str, Any]] = [{"type": "text", "text": prompt}]
        for idx, frame in enumerate(keyframes, start=1):
            content.append(
                {
                    "type": "text",
                    "text": (
                        f"Screenshot for keyframe {idx} (idx={idx}, "
                        f"timestamp_sec={frame.timestamp_sec:.3f}, "
                        f"motion_score={frame.motion_score:.3f}). "
                        f"Describe exactly what you see on this Android screen:"
                    ),
                }
            )
            content.append(
                {
                    "type": "image_url",
                    "image_url": {"url": self._encode_keyframe_data_url(frame)},
                }
            )
        return content

    def _encode_keyframe_data_url(self, frame: Keyframe) -> str:
        image = frame.image_bgr
        h, w = image.shape[:2]
        max_dim = 768
        if max(h, w) > max_dim:
            scale = max_dim / float(max(h, w))
            image = cv2.resize(image, (int(w * scale), int(h * scale)), interpolation=cv2.INTER_AREA)

        ok, encoded = cv2.imencode(".jpg", image, [int(cv2.IMWRITE_JPEG_QUALITY), 80])
        if not ok:
            raise ProviderError("Failed to encode keyframe image for Llama vision request.")
        data_b64 = base64.b64encode(encoded.tobytes()).decode("ascii")
        return f"data:image/jpeg;base64,{data_b64}"

    def _normalize_action_type(self, action_type: str) -> str:
        lowered = action_type.strip().lower().replace(" ", "_")
        mapping = {
            "click": "tap",
            "press": "tap",
            "input": "type",
            "enter_text": "type",
            "scroll_down": "scroll",
            "swipe_up": "swipe",
            "swipe_down": "swipe",
            "app_launch": "launch",
            "launch_app": "launch",
        }
        normalized = mapping.get(lowered, lowered)
        allowed = {
            "launch",
            "tap",
            "type",
            "swipe",
            "scroll",
            "wait",
            "long_press",
            "back",
            "open_menu",
            "select",
        }
        if normalized not in allowed:
            return ""
        return normalized

    def _is_placeholder_text(self, value: str) -> bool:
        lowered = value.strip().lower()
        return lowered in {"", "none", "n/a", "na", "unknown", "null"}


class QwenProvider(BaseLLMProvider):
    """Qwen vision provider via Ollama (OpenAI-compatible endpoint).

    Reuses the same multimodal content format and streaming logic as LlamaProvider.
    Environment variables: QWEN_BASE_URL (required), QWEN_API_KEY (optional).
    """

    def __init__(
        self,
        llm_name: str,
        llm_model: str,
        env: Dict[str, str],
        logger: logging.Logger,
        action_prompt_path: Path,
    ) -> None:
        super().__init__(llm_name, llm_model, env, logger)
        self.action_prompt_path = action_prompt_path

    def validate_connection(self) -> None:
        try:
            assert_llama_accessible(
                base_url=str(self.env.get("QWEN_BASE_URL", "")),
                model=self.llm_model,
                api_key=str(self.env.get("QWEN_API_KEY", "")),
                timeout_sec=30,
            )
        except LlamaPrereqError as exc:
            raise ProviderError(str(exc)) from exc

    def infer_actions(self, keyframes: List[Keyframe]) -> List[ProviderAction]:
        if not keyframes:
            return []

        self.logger.info(
            "Sending Qwen inference request | model=%s | keyframes=%d",
            self.llm_model,
            len(keyframes),
        )
        prompt = self._build_action_prompt(keyframes)
        raw_timeout = str(self.env.get("QWEN_TIMEOUT_SEC", "")).strip()
        timeout_sec: int | None = None
        if raw_timeout:
            try:
                parsed = int(raw_timeout)
                timeout_sec = parsed if parsed > 0 else None
            except ValueError:
                pass
        self.logger.info(
            "Qwen inference timeout | timeout_sec=%s",
            timeout_sec if timeout_sec is not None else "unlimited",
        )
        try:
            raw_text = self._call_qwen(
                prompt=prompt,
                keyframes=keyframes,
                timeout_sec=timeout_sec,
                request_kind="action_inference",
            )
            self.raw_llm_response = raw_text
            parsed = self._parse_actions(raw_text, keyframes)
            if parsed:
                self.logger.info(
                    "Qwen inference parsed successfully | parsed_actions=%d",
                    len(parsed),
                )
                return parsed
            self.logger.warning(
                "Qwen response could not be parsed into actions; falling back to deterministic heuristic."
            )
        except ProviderError as exc:
            self.logger.warning(
                "Qwen inference request failed (%s); falling back to deterministic heuristic.",
                exc,
            )

        return self._deterministic_fallback(keyframes, source="qwen_fallback")

    def _build_action_prompt(self, keyframes: List[Keyframe]) -> str:
        keyframe_lines = [
            (
                f"- idx={idx + 1}, timestamp_sec={frame.timestamp_sec:.3f}, "
                f"motion_score={frame.motion_score:.3f}"
            )
            for idx, frame in enumerate(keyframes)
        ]
        joined = "\n".join(keyframe_lines)
        try:
            template = self.action_prompt_path.read_text(encoding="utf-8")
        except OSError as exc:
            raise ProviderError(
                f"Failed to read action_prompt_file: {self.action_prompt_path}"
            ) from exc

        if "{KEYFRAMES}" in template:
            return template.replace("{KEYFRAMES}", joined)
        if "{keyframes}" in template:
            return template.replace("{keyframes}", joined)
        if not template.endswith("\n"):
            template += "\n"
        return f"{template}\nKeyframes to analyse:\n{joined}\n"

    def _call_qwen(
        self,
        prompt: str,
        keyframes: List[Keyframe] | None,
        timeout_sec: int | None,
        request_kind: str,
    ) -> str:
        base_url = str(self.env.get("QWEN_BASE_URL", "")).strip()
        if not base_url:
            raise ProviderError("Missing QWEN_BASE_URL for qwen provider.")

        normalized_base = base_url.rstrip("/")
        if normalized_base.endswith("/v1/chat/completions"):
            url = normalized_base
        elif normalized_base.endswith("/v1"):
            url = f"{normalized_base}/chat/completions"
        else:
            url = f"{normalized_base}/v1/chat/completions"

        headers = {"Content-Type": "application/json"}
        api_key = str(self.env.get("QWEN_API_KEY", "")).strip()
        if api_key:
            headers["Authorization"] = f"Bearer {api_key}"

        payload: Dict[str, Any] = {
            "model": self.llm_model,
            "temperature": 0.1,
            "repeat_penalty": 1.3,
            "stream": True,
            # Cap context window to avoid over-allocating VRAM on Apple Silicon.
            # Qwen2.5-VL allocates KV cache proportional to num_ctx; 4096 is ample
            # for the prompt + image tokens + JSON response.
            "num_ctx": 4096,
        }
        if self._supports_vision() and keyframes:
            payload["messages"] = [
                {
                    "role": "user",
                    "content": self._build_multimodal_content(prompt, keyframes),
                }
            ]
        else:
            payload["messages"] = [{"role": "user", "content": prompt}]

        payload_bytes = json.dumps(payload).encode("utf-8")
        req = url_request.Request(
            url=url,
            data=payload_bytes,
            headers=headers,
            method="POST",
        )

        self.logger.info(
            "Qwen API request sent | kind=%s | model=%s | endpoint=%s | waiting for response",
            request_kind,
            self.llm_model,
            url,
        )
        start = time.perf_counter()

        heartbeat_stop = threading.Event()
        def _heartbeat() -> None:
            interval = 120
            elapsed_hb = 0
            while not heartbeat_stop.wait(timeout=interval):
                elapsed_hb += interval
                self.logger.info(
                    "Qwen still processing | kind=%s | elapsed_sec=%d | tokens_so_far=%d",
                    request_kind,
                    elapsed_hb,
                    len(accumulated_tokens),
                )
        accumulated_tokens: List[str] = []
        hb_thread = threading.Thread(target=_heartbeat, daemon=True)
        hb_thread.start()

        try:
            with url_request.urlopen(req, timeout=timeout_sec) as response:
                for raw_line in response:
                    line = raw_line.decode("utf-8").strip()
                    if not line:
                        continue
                    if line.startswith("data:"):
                        line = line[len("data:"):].strip()
                    if line in ("[DONE]", ""):
                        continue
                    try:
                        chunk = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    delta = ""
                    choices = chunk.get("choices")
                    if isinstance(choices, list) and choices:
                        delta = str(choices[0].get("delta", {}).get("content") or "")
                    if delta:
                        accumulated_tokens.append(delta)
                        self.logger.debug("Qwen token chunk | chars=%d | content=%r", len(delta), delta[:80])
        except url_error.HTTPError as exc:
            heartbeat_stop.set()
            err_body = exc.read().decode("utf-8", errors="replace")
            raise ProviderError(
                f"Qwen HTTP error {exc.code} during {request_kind}: {err_body[:300]}"
            ) from exc
        except url_error.URLError as exc:
            heartbeat_stop.set()
            raise ProviderError(f"Qwen URL error during {request_kind}: {exc}") from exc
        except TimeoutError as exc:
            heartbeat_stop.set()
            partial = "".join(accumulated_tokens)
            self.logger.warning(
                "Qwen request timed out during %s after %ss | partial_chars=%d | partial_preview=%r",
                request_kind,
                timeout_sec,
                len(partial),
                partial[:200],
            )
            raise ProviderError(
                f"Qwen request timed out during {request_kind} after {timeout_sec}s"
            ) from exc
        finally:
            heartbeat_stop.set()

        elapsed = time.perf_counter() - start
        full_text = "".join(accumulated_tokens)
        self.logger.info(
            "Qwen API response complete | kind=%s | elapsed_sec=%.2f | total_chars=%d",
            request_kind,
            elapsed,
            len(full_text),
        )
        return full_text

    def _parse_actions(
        self,
        raw_text: str,
        keyframes: List[Keyframe],
    ) -> List[ProviderAction] | None:
        # Reuse LlamaProvider parse logic verbatim (same JSON schema expected)
        text = raw_text.strip()
        if "```" in text:
            chunks = text.split("```")
            for chunk in chunks:
                cleaned = chunk.strip()
                if cleaned.startswith("json"):
                    cleaned = cleaned[4:].strip()
                if cleaned.startswith("["):
                    text = cleaned
                    break
        if not text.startswith("["):
            bracket_idx = text.find("\n[")
            if bracket_idx != -1:
                text = text[bracket_idx:].strip()
            else:
                return None

        bracket_end = text.rfind("]")
        if bracket_end != -1:
            text = text[: bracket_end + 1]

        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            return None
        if not isinstance(parsed, list):
            return None

        actions: List[ProviderAction] = []
        for idx, item in enumerate(parsed):
            if idx >= len(keyframes):
                break
            if not isinstance(item, dict):
                return None
            screen_description = str(item.get("screen_description", "")).strip()
            action_type = self._normalize_action_type(str(item.get("action_type", "")).strip())
            target = str(item.get("target", "")).strip()
            details = str(item.get("details", "")).strip()
            confidence_raw = item.get("confidence", 0.5)
            try:
                confidence = float(confidence_raw)
            except (TypeError, ValueError):
                confidence = 0.5

            if not action_type:
                return None
            if self._is_placeholder_text(screen_description):
                return None
            if self._is_placeholder_text(details):
                return None
            if self._is_placeholder_text(target) and action_type != "launch":
                return None
            actions.append(
                ProviderAction(
                    screen_description=screen_description
                    or f"Qwen-inferred state for keyframe {idx + 1}",
                    action_type=action_type,
                    target=target or f"ui_target_{idx + 1}",
                    details=details or "No additional details provided by Qwen.",
                    confidence=max(0.0, min(1.0, confidence)),
                )
            )

        if not actions:
            return None
        while len(actions) < len(keyframes):
            fallback = self._deterministic_fallback(
                [keyframes[len(actions)]], source="qwen_partial_fallback"
            )[0]
            actions.append(fallback)
        return actions

    def _supports_vision(self) -> bool:
        model = self.llm_model.lower()
        _VISION_MARKERS = ("vision", "vl", "llava", "minicpm-v", "minicpmv", "gemma3", "gemma-3")
        return any(m in model for m in _VISION_MARKERS)

    def _build_multimodal_content(
        self,
        prompt: str,
        keyframes: List[Keyframe],
    ) -> List[Dict[str, Any]]:
        content: List[Dict[str, Any]] = [{"type": "text", "text": prompt}]
        for idx, frame in enumerate(keyframes, start=1):
            content.append(
                {
                    "type": "text",
                    "text": (
                        f"Screenshot for keyframe {idx} (idx={idx}, "
                        f"timestamp_sec={frame.timestamp_sec:.3f}, "
                        f"motion_score={frame.motion_score:.3f}). "
                        f"Describe exactly what you see on this Android screen:"
                    ),
                }
            )
            content.append(
                {
                    "type": "image_url",
                    "image_url": {"url": self._encode_keyframe_data_url(frame)},
                }
            )
        return content

    def _encode_keyframe_data_url(self, frame: Keyframe) -> str:
        image = frame.image_bgr
        h, w = image.shape[:2]
        # Use 512px max (vs 768 for Llama) to reduce VRAM pressure on Apple Silicon
        # when sending multiple images. Qwen2.5-VL performs well at 512px for UI analysis.
        max_dim = 512
        if max(h, w) > max_dim:
            scale = max_dim / float(max(h, w))
            image = cv2.resize(image, (int(w * scale), int(h * scale)), interpolation=cv2.INTER_AREA)

        ok, encoded = cv2.imencode(".jpg", image, [int(cv2.IMWRITE_JPEG_QUALITY), 80])
        if not ok:
            raise ProviderError("Failed to encode keyframe image for Qwen vision request.")
        data_b64 = base64.b64encode(encoded.tobytes()).decode("ascii")
        return f"data:image/jpeg;base64,{data_b64}"

    def _normalize_action_type(self, action_type: str) -> str:
        lowered = action_type.strip().lower().replace(" ", "_")
        mapping = {
            "click": "tap",
            "press": "tap",
            "input": "type",
            "enter_text": "type",
            "scroll_down": "scroll",
            "swipe_up": "swipe",
            "swipe_down": "swipe",
            "app_launch": "launch",
            "launch_app": "launch",
        }
        normalized = mapping.get(lowered, lowered)
        allowed = {
            "launch",
            "tap",
            "type",
            "swipe",
            "scroll",
            "wait",
            "long_press",
            "back",
            "open_menu",
            "select",
        }
        if normalized not in allowed:
            return ""
        return normalized

    def _is_placeholder_text(self, value: str) -> bool:
        lowered = value.strip().lower()
        return lowered in {"", "none", "n/a", "na", "unknown", "null"}


class LLaVAProvider(LlamaProvider):
    """LLaVA 1.6 via Ollama — thin subclass of LlamaProvider.

    LLaVA uses the same OpenAI-compatible endpoint and env vars as Llama (LLAMA_BASE_URL).
    Registered under llm: "llava" in config.yml.
    """

    def infer_actions(self, keyframes: List[Keyframe]) -> List[ProviderAction]:
        if not keyframes:
            return []
        self.logger.info(
            "Sending LLaVA inference request | model=%s | keyframes=%d",
            self.llm_model,
            len(keyframes),
        )
        prompt = self._build_action_prompt(keyframes)
        raw_timeout = str(self.env.get("LLAMA_TIMEOUT_SEC", "")).strip()
        timeout_sec: int | None = None
        if raw_timeout:
            try:
                parsed = int(raw_timeout)
                timeout_sec = parsed if parsed > 0 else None
            except ValueError:
                pass
        try:
            raw_text = self._call_llama(
                prompt=prompt,
                keyframes=keyframes,
                timeout_sec=timeout_sec,
                request_kind="action_inference",
            )
            self.raw_llm_response = raw_text
            parsed = self._parse_actions(raw_text, keyframes)
            if parsed:
                self.logger.info(
                    "LLaVA inference parsed successfully | parsed_actions=%d", len(parsed)
                )
                return parsed
            self.logger.warning(
                "LLaVA response could not be parsed; falling back to deterministic heuristic."
            )
        except ProviderError as exc:
            self.logger.warning(
                "LLaVA inference request failed (%s); falling back to deterministic heuristic.", exc
            )
        return self._deterministic_fallback(keyframes, source="llava_fallback")


class MiniCPMProvider(BaseLLMProvider):
    """MiniCPM-V 2.6 via Ollama — excellent for dense UI screenshots.

    Uses LLAMA_BASE_URL (same local Ollama endpoint). Registered under llm: "minicpm".
    Image size capped at 448px — MiniCPM-V uses 448x448 tiles natively.
    num_ctx capped at 4096 to prevent VRAM over-allocation on Apple Silicon.
    """

    def __init__(
        self,
        llm_name: str,
        llm_model: str,
        env: Dict[str, str],
        logger: logging.Logger,
        action_prompt_path: Path,
    ) -> None:
        super().__init__(llm_name, llm_model, env, logger)
        self.action_prompt_path = action_prompt_path

    def validate_connection(self) -> None:
        try:
            assert_llama_accessible(
                base_url=str(self.env.get("LLAMA_BASE_URL", "")),
                model=self.llm_model,
                api_key=str(self.env.get("LLAMA_API_KEY", "")),
                timeout_sec=30,
            )
        except LlamaPrereqError as exc:
            raise ProviderError(str(exc)) from exc

    def infer_actions(self, keyframes: List[Keyframe]) -> List[ProviderAction]:
        if not keyframes:
            return []
        self.logger.info(
            "Sending MiniCPM inference request | model=%s | keyframes=%d",
            self.llm_model,
            len(keyframes),
        )
        prompt = self._build_action_prompt(keyframes)
        raw_timeout = str(self.env.get("LLAMA_TIMEOUT_SEC", "")).strip()
        timeout_sec: int | None = None
        if raw_timeout:
            try:
                parsed = int(raw_timeout)
                timeout_sec = parsed if parsed > 0 else None
            except ValueError:
                pass
        try:
            raw_text = self._call_minicpm(
                prompt=prompt,
                keyframes=keyframes,
                timeout_sec=timeout_sec,
                request_kind="action_inference",
            )
            self.raw_llm_response = raw_text
            parsed = self._parse_actions(raw_text, keyframes)
            if parsed:
                self.logger.info(
                    "MiniCPM inference parsed successfully | parsed_actions=%d", len(parsed)
                )
                return parsed
            self.logger.warning(
                "MiniCPM response could not be parsed; falling back to deterministic heuristic."
            )
        except ProviderError as exc:
            self.logger.warning(
                "MiniCPM inference request failed (%s); falling back to deterministic heuristic.", exc
            )
        return self._deterministic_fallback(keyframes, source="minicpm_fallback")

    def _build_action_prompt(self, keyframes: List[Keyframe]) -> str:
        keyframe_lines = [
            f"- idx={idx + 1}, timestamp_sec={frame.timestamp_sec:.3f}, motion_score={frame.motion_score:.3f}"
            for idx, frame in enumerate(keyframes)
        ]
        joined = "\n".join(keyframe_lines)
        try:
            template = self.action_prompt_path.read_text(encoding="utf-8")
        except OSError as exc:
            raise ProviderError(f"Failed to read action_prompt_file: {self.action_prompt_path}") from exc
        if "{KEYFRAMES}" in template:
            return template.replace("{KEYFRAMES}", joined)
        if "{keyframes}" in template:
            return template.replace("{keyframes}", joined)
        if not template.endswith("\n"):
            template += "\n"
        return f"{template}\nKeyframes to analyse:\n{joined}\n"

    def _call_minicpm(
        self,
        prompt: str,
        keyframes: List[Keyframe] | None,
        timeout_sec: int | None,
        request_kind: str,
    ) -> str:
        base_url = str(self.env.get("LLAMA_BASE_URL", "")).strip()
        if not base_url:
            raise ProviderError("Missing LLAMA_BASE_URL for minicpm provider.")

        normalized_base = base_url.rstrip("/")
        if normalized_base.endswith("/v1/chat/completions"):
            url = normalized_base
        elif normalized_base.endswith("/v1"):
            url = f"{normalized_base}/chat/completions"
        else:
            url = f"{normalized_base}/v1/chat/completions"

        headers = {"Content-Type": "application/json"}
        api_key = str(self.env.get("LLAMA_API_KEY", "")).strip()
        if api_key:
            headers["Authorization"] = f"Bearer {api_key}"

        payload: Dict[str, Any] = {
            "model": self.llm_model,
            "temperature": 0.1,
            "repeat_penalty": 1.3,
            "stream": True,
            # MiniCPM-V uses 448x448 tiles; cap context to avoid VRAM over-allocation.
            "num_ctx": 4096,
        }
        if keyframes:
            payload["messages"] = [
                {"role": "user", "content": self._build_multimodal_content(prompt, keyframes)}
            ]
        else:
            payload["messages"] = [{"role": "user", "content": prompt}]

        payload_bytes = json.dumps(payload).encode("utf-8")
        req = url_request.Request(url=url, data=payload_bytes, headers=headers, method="POST")

        self.logger.info(
            "MiniCPM API request sent | kind=%s | model=%s | endpoint=%s | waiting for response",
            request_kind, self.llm_model, url,
        )
        start = time.perf_counter()
        heartbeat_stop = threading.Event()

        def _heartbeat() -> None:
            interval = 120
            elapsed_hb = 0
            while not heartbeat_stop.wait(timeout=interval):
                elapsed_hb += interval
                self.logger.info(
                    "MiniCPM still processing | kind=%s | elapsed_sec=%d | tokens_so_far=%d",
                    request_kind, elapsed_hb, len(accumulated_tokens),
                )

        accumulated_tokens: List[str] = []
        hb_thread = threading.Thread(target=_heartbeat, daemon=True)
        hb_thread.start()
        try:
            with url_request.urlopen(req, timeout=timeout_sec) as response:
                for raw_line in response:
                    line = raw_line.decode("utf-8").strip()
                    if not line:
                        continue
                    if line.startswith("data:"):
                        line = line[len("data:"):].strip()
                    if line in ("[DONE]", ""):
                        continue
                    try:
                        chunk = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    choices = chunk.get("choices")
                    if isinstance(choices, list) and choices:
                        delta = str(choices[0].get("delta", {}).get("content") or "")
                        if delta:
                            accumulated_tokens.append(delta)
        except url_error.HTTPError as exc:
            heartbeat_stop.set()
            err_body = exc.read().decode("utf-8", errors="replace")
            raise ProviderError(f"MiniCPM HTTP error {exc.code} during {request_kind}: {err_body[:300]}") from exc
        except url_error.URLError as exc:
            heartbeat_stop.set()
            raise ProviderError(f"MiniCPM URL error during {request_kind}: {exc}") from exc
        except TimeoutError as exc:
            heartbeat_stop.set()
            raise ProviderError(f"MiniCPM request timed out during {request_kind} after {timeout_sec}s") from exc
        finally:
            heartbeat_stop.set()

        elapsed = time.perf_counter() - start
        full_text = "".join(accumulated_tokens)
        self.logger.info(
            "MiniCPM API response complete | kind=%s | elapsed_sec=%.2f | total_chars=%d",
            request_kind, elapsed, len(full_text),
        )
        return full_text

    def _build_multimodal_content(self, prompt: str, keyframes: List[Keyframe]) -> List[Dict[str, Any]]:
        content: List[Dict[str, Any]] = [{"type": "text", "text": prompt}]
        for idx, frame in enumerate(keyframes, start=1):
            content.append({
                "type": "text",
                "text": (
                    f"Screenshot for keyframe {idx} (idx={idx}, "
                    f"timestamp_sec={frame.timestamp_sec:.3f}, "
                    f"motion_score={frame.motion_score:.3f}). "
                    f"Describe exactly what you see on this Android screen:"
                ),
            })
            content.append({
                "type": "image_url",
                "image_url": {"url": self._encode_keyframe_data_url(frame)},
            })
        return content

    def _encode_keyframe_data_url(self, frame: Keyframe) -> str:
        image = frame.image_bgr
        h, w = image.shape[:2]
        # MiniCPM-V uses 448x448 tiles natively; 448px max keeps one tile per image.
        max_dim = 448
        if max(h, w) > max_dim:
            scale = max_dim / float(max(h, w))
            image = cv2.resize(image, (int(w * scale), int(h * scale)), interpolation=cv2.INTER_AREA)
        ok, encoded = cv2.imencode(".jpg", image, [int(cv2.IMWRITE_JPEG_QUALITY), 80])
        if not ok:
            raise ProviderError("Failed to encode keyframe image for MiniCPM vision request.")
        data_b64 = base64.b64encode(encoded.tobytes()).decode("ascii")
        return f"data:image/jpeg;base64,{data_b64}"

    def _parse_actions(self, raw_text: str, keyframes: List[Keyframe]) -> List[ProviderAction] | None:
        text = raw_text.strip()
        if "```" in text:
            chunks = text.split("```")
            for chunk in chunks:
                cleaned = chunk.strip()
                if cleaned.startswith("json"):
                    cleaned = cleaned[4:].strip()
                if cleaned.startswith("["):
                    text = cleaned
                    break
        if not text.startswith("["):
            bracket_idx = text.find("\n[")
            if bracket_idx != -1:
                text = text[bracket_idx:].strip()
            else:
                return None
        bracket_end = text.rfind("]")
        if bracket_end != -1:
            text = text[: bracket_end + 1]
        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            return None
        if not isinstance(parsed, list):
            return None
        actions: List[ProviderAction] = []
        for idx, item in enumerate(parsed):
            if idx >= len(keyframes):
                break
            if not isinstance(item, dict):
                return None
            screen_description = str(item.get("screen_description", "")).strip()
            action_type = self._normalize_action_type(str(item.get("action_type", "")).strip())
            target = str(item.get("target", "")).strip()
            details = str(item.get("details", "")).strip()
            confidence_raw = item.get("confidence", 0.5)
            try:
                confidence = float(confidence_raw)
            except (TypeError, ValueError):
                confidence = 0.5
            if not action_type:
                return None
            if self._is_placeholder_text(screen_description):
                return None
            if self._is_placeholder_text(details):
                return None
            if self._is_placeholder_text(target) and action_type != "launch":
                return None
            actions.append(ProviderAction(
                screen_description=screen_description or f"MiniCPM-inferred state for keyframe {idx + 1}",
                action_type=action_type,
                target=target or f"ui_target_{idx + 1}",
                details=details or "No additional details provided by MiniCPM.",
                confidence=max(0.0, min(1.0, confidence)),
            ))
        if not actions:
            return None
        while len(actions) < len(keyframes):
            fallback = self._deterministic_fallback([keyframes[len(actions)]], source="minicpm_partial_fallback")[0]
            actions.append(fallback)
        return actions

    def _normalize_action_type(self, action_type: str) -> str:
        lowered = action_type.strip().lower().replace(" ", "_")
        mapping = {
            "click": "tap", "press": "tap", "input": "type", "enter_text": "type",
            "scroll_down": "scroll", "swipe_up": "swipe", "swipe_down": "swipe",
            "app_launch": "launch", "launch_app": "launch",
        }
        normalized = mapping.get(lowered, lowered)
        allowed = {"launch", "tap", "type", "swipe", "scroll", "wait", "long_press", "back", "open_menu", "select"}
        return normalized if normalized in allowed else ""

    def _is_placeholder_text(self, value: str) -> bool:
        return value.strip().lower() in {"", "none", "n/a", "na", "unknown", "null"}


class GemmaProvider(BaseLLMProvider):
    """Gemma 3 (vision) via Ollama — Google's multimodal model.

    Uses LLAMA_BASE_URL (same local Ollama endpoint). Registered under llm: "gemma".
    Image size capped at 512px; num_ctx capped at 4096 for Apple Silicon.
    """

    def __init__(
        self,
        llm_name: str,
        llm_model: str,
        env: Dict[str, str],
        logger: logging.Logger,
        action_prompt_path: Path,
    ) -> None:
        super().__init__(llm_name, llm_model, env, logger)
        self.action_prompt_path = action_prompt_path

    def validate_connection(self) -> None:
        try:
            assert_llama_accessible(
                base_url=str(self.env.get("LLAMA_BASE_URL", "")),
                model=self.llm_model,
                api_key=str(self.env.get("LLAMA_API_KEY", "")),
                timeout_sec=30,
            )
        except LlamaPrereqError as exc:
            raise ProviderError(str(exc)) from exc

    def infer_actions(self, keyframes: List[Keyframe]) -> List[ProviderAction]:
        if not keyframes:
            return []
        self.logger.info(
            "Sending Gemma inference request | model=%s | keyframes=%d",
            self.llm_model,
            len(keyframes),
        )
        prompt = self._build_action_prompt(keyframes)
        raw_timeout = str(self.env.get("LLAMA_TIMEOUT_SEC", "")).strip()
        timeout_sec: int | None = None
        if raw_timeout:
            try:
                parsed = int(raw_timeout)
                timeout_sec = parsed if parsed > 0 else None
            except ValueError:
                pass
        try:
            raw_text = self._call_gemma(
                prompt=prompt,
                keyframes=keyframes,
                timeout_sec=timeout_sec,
                request_kind="action_inference",
            )
            self.raw_llm_response = raw_text
            parsed = self._parse_actions(raw_text, keyframes)
            if parsed:
                self.logger.info(
                    "Gemma inference parsed successfully | parsed_actions=%d", len(parsed)
                )
                return parsed
            self.logger.warning(
                "Gemma response could not be parsed; falling back to deterministic heuristic."
            )
        except ProviderError as exc:
            self.logger.warning(
                "Gemma inference request failed (%s); falling back to deterministic heuristic.", exc
            )
        return self._deterministic_fallback(keyframes, source="gemma_fallback")

    def _build_action_prompt(self, keyframes: List[Keyframe]) -> str:
        keyframe_lines = [
            f"- idx={idx + 1}, timestamp_sec={frame.timestamp_sec:.3f}, motion_score={frame.motion_score:.3f}"
            for idx, frame in enumerate(keyframes)
        ]
        joined = "\n".join(keyframe_lines)
        try:
            template = self.action_prompt_path.read_text(encoding="utf-8")
        except OSError as exc:
            raise ProviderError(f"Failed to read action_prompt_file: {self.action_prompt_path}") from exc
        if "{KEYFRAMES}" in template:
            return template.replace("{KEYFRAMES}", joined)
        if "{keyframes}" in template:
            return template.replace("{keyframes}", joined)
        if not template.endswith("\n"):
            template += "\n"
        return f"{template}\nKeyframes to analyse:\n{joined}\n"

    def _call_gemma(
        self,
        prompt: str,
        keyframes: List[Keyframe] | None,
        timeout_sec: int | None,
        request_kind: str,
    ) -> str:
        base_url = str(self.env.get("LLAMA_BASE_URL", "")).strip()
        if not base_url:
            raise ProviderError("Missing LLAMA_BASE_URL for gemma provider.")

        normalized_base = base_url.rstrip("/")
        if normalized_base.endswith("/v1/chat/completions"):
            url = normalized_base
        elif normalized_base.endswith("/v1"):
            url = f"{normalized_base}/chat/completions"
        else:
            url = f"{normalized_base}/v1/chat/completions"

        headers = {"Content-Type": "application/json"}
        api_key = str(self.env.get("LLAMA_API_KEY", "")).strip()
        if api_key:
            headers["Authorization"] = f"Bearer {api_key}"

        payload: Dict[str, Any] = {
            "model": self.llm_model,
            "temperature": 0.1,
            "repeat_penalty": 1.3,
            "stream": True,
            # Cap context to avoid VRAM over-allocation on Apple Silicon.
            "num_ctx": 4096,
        }
        if keyframes:
            payload["messages"] = [
                {"role": "user", "content": self._build_multimodal_content(prompt, keyframes)}
            ]
        else:
            payload["messages"] = [{"role": "user", "content": prompt}]

        payload_bytes = json.dumps(payload).encode("utf-8")
        req = url_request.Request(url=url, data=payload_bytes, headers=headers, method="POST")

        self.logger.info(
            "Gemma API request sent | kind=%s | model=%s | endpoint=%s | waiting for response",
            request_kind, self.llm_model, url,
        )
        start = time.perf_counter()
        heartbeat_stop = threading.Event()

        def _heartbeat() -> None:
            interval = 120
            elapsed_hb = 0
            while not heartbeat_stop.wait(timeout=interval):
                elapsed_hb += interval
                self.logger.info(
                    "Gemma still processing | kind=%s | elapsed_sec=%d | tokens_so_far=%d",
                    request_kind, elapsed_hb, len(accumulated_tokens),
                )

        accumulated_tokens: List[str] = []
        hb_thread = threading.Thread(target=_heartbeat, daemon=True)
        hb_thread.start()
        try:
            with url_request.urlopen(req, timeout=timeout_sec) as response:
                for raw_line in response:
                    line = raw_line.decode("utf-8").strip()
                    if not line:
                        continue
                    if line.startswith("data:"):
                        line = line[len("data:"):].strip()
                    if line in ("[DONE]", ""):
                        continue
                    try:
                        chunk = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    choices = chunk.get("choices")
                    if isinstance(choices, list) and choices:
                        delta = str(choices[0].get("delta", {}).get("content") or "")
                        if delta:
                            accumulated_tokens.append(delta)
        except url_error.HTTPError as exc:
            heartbeat_stop.set()
            err_body = exc.read().decode("utf-8", errors="replace")
            raise ProviderError(f"Gemma HTTP error {exc.code} during {request_kind}: {err_body[:300]}") from exc
        except url_error.URLError as exc:
            heartbeat_stop.set()
            raise ProviderError(f"Gemma URL error during {request_kind}: {exc}") from exc
        except TimeoutError as exc:
            heartbeat_stop.set()
            raise ProviderError(f"Gemma request timed out during {request_kind} after {timeout_sec}s") from exc
        finally:
            heartbeat_stop.set()

        elapsed = time.perf_counter() - start
        full_text = "".join(accumulated_tokens)
        self.logger.info(
            "Gemma API response complete | kind=%s | elapsed_sec=%.2f | total_chars=%d",
            request_kind, elapsed, len(full_text),
        )
        return full_text

    def _build_multimodal_content(self, prompt: str, keyframes: List[Keyframe]) -> List[Dict[str, Any]]:
        content: List[Dict[str, Any]] = [{"type": "text", "text": prompt}]
        for idx, frame in enumerate(keyframes, start=1):
            content.append({
                "type": "text",
                "text": (
                    f"Screenshot for keyframe {idx} (idx={idx}, "
                    f"timestamp_sec={frame.timestamp_sec:.3f}, "
                    f"motion_score={frame.motion_score:.3f}). "
                    f"Describe exactly what you see on this Android screen:"
                ),
            })
            content.append({
                "type": "image_url",
                "image_url": {"url": self._encode_keyframe_data_url(frame)},
            })
        return content

    def _encode_keyframe_data_url(self, frame: Keyframe) -> str:
        image = frame.image_bgr
        h, w = image.shape[:2]
        max_dim = 512
        if max(h, w) > max_dim:
            scale = max_dim / float(max(h, w))
            image = cv2.resize(image, (int(w * scale), int(h * scale)), interpolation=cv2.INTER_AREA)
        ok, encoded = cv2.imencode(".jpg", image, [int(cv2.IMWRITE_JPEG_QUALITY), 80])
        if not ok:
            raise ProviderError("Failed to encode keyframe image for Gemma vision request.")
        data_b64 = base64.b64encode(encoded.tobytes()).decode("ascii")
        return f"data:image/jpeg;base64,{data_b64}"

    def _parse_actions(self, raw_text: str, keyframes: List[Keyframe]) -> List[ProviderAction] | None:
        text = raw_text.strip()
        if "```" in text:
            chunks = text.split("```")
            for chunk in chunks:
                cleaned = chunk.strip()
                if cleaned.startswith("json"):
                    cleaned = cleaned[4:].strip()
                if cleaned.startswith("["):
                    text = cleaned
                    break
        if not text.startswith("["):
            bracket_idx = text.find("\n[")
            if bracket_idx != -1:
                text = text[bracket_idx:].strip()
            else:
                return None
        bracket_end = text.rfind("]")
        if bracket_end != -1:
            text = text[: bracket_end + 1]
        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            return None
        if not isinstance(parsed, list):
            return None
        actions: List[ProviderAction] = []
        for idx, item in enumerate(parsed):
            if idx >= len(keyframes):
                break
            if not isinstance(item, dict):
                return None
            screen_description = str(item.get("screen_description", "")).strip()
            action_type = self._normalize_action_type(str(item.get("action_type", "")).strip())
            target = str(item.get("target", "")).strip()
            details = str(item.get("details", "")).strip()
            confidence_raw = item.get("confidence", 0.5)
            try:
                confidence = float(confidence_raw)
            except (TypeError, ValueError):
                confidence = 0.5
            if not action_type:
                return None
            if self._is_placeholder_text(screen_description):
                return None
            if self._is_placeholder_text(details):
                return None
            if self._is_placeholder_text(target) and action_type != "launch":
                return None
            actions.append(ProviderAction(
                screen_description=screen_description or f"Gemma-inferred state for keyframe {idx + 1}",
                action_type=action_type,
                target=target or f"ui_target_{idx + 1}",
                details=details or "No additional details provided by Gemma.",
                confidence=max(0.0, min(1.0, confidence)),
            ))
        if not actions:
            return None
        while len(actions) < len(keyframes):
            fallback = self._deterministic_fallback([keyframes[len(actions)]], source="gemma_partial_fallback")[0]
            actions.append(fallback)
        return actions

    def _normalize_action_type(self, action_type: str) -> str:
        lowered = action_type.strip().lower().replace(" ", "_")
        mapping = {
            "click": "tap", "press": "tap", "input": "type", "enter_text": "type",
            "scroll_down": "scroll", "swipe_up": "swipe", "swipe_down": "swipe",
            "app_launch": "launch", "launch_app": "launch",
        }
        normalized = mapping.get(lowered, lowered)
        allowed = {"launch", "tap", "type", "swipe", "scroll", "wait", "long_press", "back", "open_menu", "select"}
        return normalized if normalized in allowed else ""

    def _is_placeholder_text(self, value: str) -> bool:
        return value.strip().lower() in {"", "none", "n/a", "na", "unknown", "null"}


def create_provider(
    llm_name: str,
    llm_model: str,
    env: Dict[str, str],
    logger: logging.Logger,
    llm_prompt_file: Path | None = None,
    video_mode: bool = False,
) -> BaseLLMProvider:
    provider_key = llm_name.lower()
    default_prompt = Path("src_llm/input/prompts/llama_action_prompt_gemini_2.txt")

    if provider_key == "gemini":
        if video_mode:
            return GeminiVideoProvider(provider_key, llm_model, env, logger, llm_prompt_file)
        return GeminiProvider(provider_key, llm_model, env, logger)
    if provider_key in {"sonnet", "claude"}:
        return SonnetProvider(provider_key, llm_model, env, logger)
    if provider_key == "llama":
        prompt_path = llm_prompt_file or Path(
            "src_llm/input/prompts/llama_action_prompt.txt"
        )
        return LlamaProvider(provider_key, llm_model, env, logger, prompt_path)
    if provider_key == "llava":
        prompt_path = llm_prompt_file or default_prompt
        return LLaVAProvider(provider_key, llm_model, env, logger, prompt_path)
    if provider_key == "minicpm":
        prompt_path = llm_prompt_file or default_prompt
        return MiniCPMProvider(provider_key, llm_model, env, logger, prompt_path)
    if provider_key == "gemma":
        prompt_path = llm_prompt_file or default_prompt
        return GemmaProvider(provider_key, llm_model, env, logger, prompt_path)
    if provider_key == "qwen":
        prompt_path = llm_prompt_file or default_prompt
        return QwenProvider(provider_key, llm_model, env, logger, prompt_path)

    supported = "gemini, sonnet/claude, llama, llava, minicpm, gemma, qwen"
    raise ValueError(f"Unsupported llm provider '{llm_name}'. Supported: {supported}")
