from __future__ import annotations

import json
import logging
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Dict, List
from urllib import error as url_error
from urllib import request as url_request

from gifdroid_llm.keyframes import Keyframe


@dataclass(frozen=True)
class ProviderAction:
    screen_description: str
    action_type: str
    target: str
    details: str
    confidence: float


class ProviderError(RuntimeError):
    """Raised for provider-specific connectivity or inference failures."""


class BaseLLMProvider(ABC):
    """Common abstraction for open/closed model adapters."""

    def __init__(
        self,
        llm_name: str,
        llm_model: str,
        env: Dict[str, str],
        logger: logging.Logger,
    ) -> None:
        self.llm_name = llm_name
        self.llm_model = llm_model
        self.env = env
        self.logger = logger

    @abstractmethod
    def infer_actions(self, keyframes: List[Keyframe]) -> List[ProviderAction]:
        """Infer action hypotheses from selected keyframes."""

    def validate_connection(self) -> None:
        """Optional provider preflight hook."""
        return None

    def _deterministic_fallback(self, keyframes: List[Keyframe], source: str) -> List[ProviderAction]:
        actions: List[ProviderAction] = []
        for idx, kf in enumerate(keyframes):
            if idx == 0:
                action_type = "launch_app"
                target = "app_entrypoint"
                details = f"{source}: initial frame likely app launch or resumed state"
                confidence = 0.88
            elif kf.motion_score >= 18:
                action_type = "tap"
                target = f"ui_element_step_{idx}"
                details = f"{source}: high visual transition suggests a click/tap action"
                confidence = 0.74
            elif kf.motion_score >= 9:
                action_type = "scroll"
                target = "scrollable_view"
                details = f"{source}: medium transition suggests scrolling/swiping"
                confidence = 0.66
            else:
                action_type = "wait"
                target = "current_screen"
                details = f"{source}: minimal transition indicates waiting or subtle input"
                confidence = 0.58

            desc = (
                f"Frame at {kf.timestamp_sec:.2f}s with motion_score={kf.motion_score:.2f}; "
                f"heuristic interpretation generated by {source}."
            )
            actions.append(
                ProviderAction(
                    screen_description=desc,
                    action_type=action_type,
                    target=target,
                    details=details,
                    confidence=confidence,
                )
            )
        return actions


class GeminiProvider(BaseLLMProvider):
    def validate_connection(self) -> None:
        self.logger.info(
            "Gemini preflight started | model=%s | validating API key and endpoint access",
            self.llm_model,
        )
        _ = self._call_gemini(
            prompt="Reply with exactly: OK",
            timeout_sec=30,
            request_kind="preflight",
        )
        self.logger.info("Gemini preflight successful | model=%s", self.llm_model)

    def infer_actions(self, keyframes: List[Keyframe]) -> List[ProviderAction]:
        if not keyframes:
            return []

        self.logger.info(
            "Sending Gemini inference request | model=%s | keyframes=%d",
            self.llm_model,
            len(keyframes),
        )
        prompt = self._build_action_prompt(keyframes)
        try:
            raw_text = self._call_gemini(
                prompt=prompt,
                timeout_sec=90,
                request_kind="action_inference",
            )
            parsed = self._parse_actions(raw_text, keyframes)
            if parsed:
                self.logger.info(
                    "Gemini inference parsed successfully | parsed_actions=%d",
                    len(parsed),
                )
                return parsed
            self.logger.warning(
                "Gemini response could not be parsed into actions; falling back to deterministic heuristic."
            )
        except ProviderError as exc:
            self.logger.warning(
                "Gemini inference request failed (%s); falling back to deterministic heuristic.",
                exc,
            )

        return self._deterministic_fallback(keyframes, source="gemini_fallback")

    def _build_action_prompt(self, keyframes: List[Keyframe]) -> str:
        keyframe_lines = [
            (
                f"- idx={idx + 1}, timestamp_sec={frame.timestamp_sec:.3f}, "
                f"motion_score={frame.motion_score:.3f}"
            )
            for idx, frame in enumerate(keyframes)
        ]
        joined = "\n".join(keyframe_lines)
        return (
            "You are inferring a mobile bug reproduction trace from frame metadata.\n"
            "Return ONLY valid JSON as an array, one object per keyframe, with keys:\n"
            "screen_description, action_type, target, details, confidence.\n"
            "confidence must be between 0 and 1.\n"
            "Keyframes:\n"
            f"{joined}\n"
        )

    def _call_gemini(self, prompt: str, timeout_sec: int, request_kind: str) -> str:
        api_key = self.env.get("GOOGLE_GENERATIVE_AI_API_KEY", "").strip()

        headers = {"Content-Type": "application/json"}
        endpoint_name = ""

        if api_key:
            auth_mode = "api_key"
            endpoint_name = "google_ai_studio"
            url = (
                "https://generativelanguage.googleapis.com/v1beta/models/"
                f"{self.llm_model}:generateContent?key={api_key}"
            )
        else:
            auth_mode = "adc_default"
            token, adc_project_id = self._build_default_adc_token()
            vertex_project_id = (
                str(self.env.get("GEMINI_VERTEX_PROJECT_ID", "")).strip() or adc_project_id
            )
            if not vertex_project_id:
                raise ProviderError(
                    "ADC did not provide a project_id and GEMINI_VERTEX_PROJECT_ID is not set."
                )
            headers["Authorization"] = f"Bearer {token}"
            location = str(self.env.get("GEMINI_VERTEX_LOCATION", "us-central1")).strip() or "us-central1"
            endpoint_name = "vertex_ai"
            url = (
                f"https://{location}-aiplatform.googleapis.com/v1/"
                f"projects/{vertex_project_id}/locations/{location}/publishers/google/models/"
                f"{self.llm_model}:generateContent"
            )
            self.logger.info(
                "Gemini ADC default credentials loaded | adc_project=%s | runtime_project=%s | token_present=%s",
                adc_project_id,
                vertex_project_id,
                bool(token),
            )
        self.logger.info(
            "Gemini auth route selected | route=%s | endpoint=%s",
            auth_mode,
            endpoint_name,
        )

        payload = {
            "contents": [{"role": "user", "parts": [{"text": prompt}]}],
            "generationConfig": {"temperature": 0.1},
        }
        payload_bytes = json.dumps(payload).encode("utf-8")
        req = url_request.Request(
            url=url,
            data=payload_bytes,
            headers=headers,
            method="POST",
        )

        self.logger.info(
            "Gemini API request sent | kind=%s | model=%s | auth=%s | endpoint=%s | waiting for response",
            request_kind,
            self.llm_model,
            auth_mode,
            endpoint_name,
        )
        start = time.perf_counter()
        try:
            with url_request.urlopen(req, timeout=timeout_sec) as response:
                response_text = response.read().decode("utf-8")
        except url_error.HTTPError as exc:
            err_body = exc.read().decode("utf-8", errors="replace")
            raise ProviderError(
                f"Gemini HTTP error {exc.code} during {request_kind}: {err_body[:300]}"
            ) from exc
        except url_error.URLError as exc:
            raise ProviderError(f"Gemini URL error during {request_kind}: {exc}") from exc
        except TimeoutError as exc:
            raise ProviderError(
                f"Gemini request timed out during {request_kind} after {timeout_sec}s"
            ) from exc

        elapsed = time.perf_counter() - start
        self.logger.info(
            "Gemini API response received | kind=%s | elapsed_sec=%.2f",
            request_kind,
            elapsed,
        )

        try:
            data = json.loads(response_text)
            return self._extract_text(data)
        except (json.JSONDecodeError, KeyError, TypeError) as exc:
            raise ProviderError(f"Invalid Gemini response format during {request_kind}") from exc

    def _build_default_adc_token(self) -> tuple[str, str | None]:
        try:
            import google.auth
            from google.auth.transport.requests import Request
        except ImportError as exc:
            raise ProviderError(
                "google-auth is required for ADC auth. "
                "Install dependencies from gifdroid_llm/requirements.txt"
            ) from exc

        try:
            creds, project_id = google.auth.default(
                scopes=["https://www.googleapis.com/auth/cloud-platform"]
            )
            creds.refresh(Request())
        except Exception as exc:
            raise ProviderError(
                "Failed to load Application Default Credentials via google.auth.default(). "
                "Set GOOGLE_APPLICATION_CREDENTIALS, run gcloud auth application-default login, "
                "or provide GOOGLE_GENERATIVE_AI_API_KEY."
            ) from exc

        token = getattr(creds, "token", None)
        if not token:
            raise ProviderError("ADC token refresh returned empty token")
        return token, project_id

    def _extract_text(self, response_data: Dict[str, object]) -> str:
        candidates = response_data.get("candidates")
        if not isinstance(candidates, list) or not candidates:
            raise ProviderError("Gemini response missing candidates")

        first = candidates[0]
        if not isinstance(first, dict):
            raise ProviderError("Gemini candidate payload has invalid structure")

        content = first.get("content")
        if not isinstance(content, dict):
            raise ProviderError("Gemini candidate missing content")

        parts = content.get("parts")
        if not isinstance(parts, list) or not parts:
            raise ProviderError("Gemini candidate missing parts")

        texts: List[str] = []
        for part in parts:
            if isinstance(part, dict):
                text = part.get("text")
                if isinstance(text, str) and text.strip():
                    texts.append(text.strip())

        if not texts:
            raise ProviderError("Gemini response contained no text parts")
        return "\n".join(texts)

    def _parse_actions(
        self,
        raw_text: str,
        keyframes: List[Keyframe],
    ) -> List[ProviderAction] | None:
        text = raw_text.strip()
        if "```" in text:
            chunks = text.split("```")
            for chunk in chunks:
                cleaned = chunk.strip()
                if cleaned.startswith("json"):
                    cleaned = cleaned[4:].strip()
                if cleaned.startswith("["):
                    text = cleaned
                    break
        if not text.startswith("["):
            return None

        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            return None
        if not isinstance(parsed, list):
            return None

        actions: List[ProviderAction] = []
        for idx, item in enumerate(parsed):
            if idx >= len(keyframes):
                break
            if not isinstance(item, dict):
                return None
            screen_description = str(item.get("screen_description", "")).strip()
            action_type = str(item.get("action_type", "")).strip()
            target = str(item.get("target", "")).strip()
            details = str(item.get("details", "")).strip()
            confidence_raw = item.get("confidence", 0.5)
            try:
                confidence = float(confidence_raw)
            except (TypeError, ValueError):
                confidence = 0.5

            if not action_type:
                return None
            actions.append(
                ProviderAction(
                    screen_description=screen_description
                    or f"Gemini-inferred state for keyframe {idx + 1}",
                    action_type=action_type,
                    target=target or f"ui_target_{idx + 1}",
                    details=details or "No additional details provided by Gemini.",
                    confidence=max(0.0, min(1.0, confidence)),
                )
            )

        if not actions:
            return None
        while len(actions) < len(keyframes):
            fallback = self._deterministic_fallback(
                [keyframes[len(actions)]], source="gemini_partial_fallback"
            )[0]
            actions.append(fallback)
        return actions


class SonnetProvider(BaseLLMProvider):
    def infer_actions(self, keyframes: List[Keyframe]) -> List[ProviderAction]:
        # TODO: Integrate Anthropic Claude/Sonnet image+text API invocation.
        self.logger.warning(
            "Sonnet provider running in stub mode (TODO API integration). model=%s",
            self.llm_model,
        )
        return self._deterministic_fallback(keyframes, source="sonnet_stub")


class LlamaProvider(BaseLLMProvider):
    def infer_actions(self, keyframes: List[Keyframe]) -> List[ProviderAction]:
        # TODO: Integrate OpenAI-compatible or vLLM-compatible endpoint for Llama.
        self.logger.warning(
            "Llama provider running in stub mode (TODO API integration). model=%s",
            self.llm_model,
        )
        return self._deterministic_fallback(keyframes, source="llama_stub")


class QwenProvider(BaseLLMProvider):
    def infer_actions(self, keyframes: List[Keyframe]) -> List[ProviderAction]:
        # TODO: Integrate Qwen endpoint (DashScope/OpenAI-compatible) API call.
        self.logger.warning(
            "Qwen provider running in stub mode (TODO API integration). model=%s",
            self.llm_model,
        )
        return self._deterministic_fallback(keyframes, source="qwen_stub")


def create_provider(
    llm_name: str,
    llm_model: str,
    env: Dict[str, str],
    logger: logging.Logger,
) -> BaseLLMProvider:
    provider_key = llm_name.lower()
    if provider_key == "gemini":
        return GeminiProvider(provider_key, llm_model, env, logger)
    if provider_key in {"sonnet", "claude"}:
        return SonnetProvider(provider_key, llm_model, env, logger)
    if provider_key == "llama":
        return LlamaProvider(provider_key, llm_model, env, logger)
    if provider_key == "qwen":
        return QwenProvider(provider_key, llm_model, env, logger)

    supported = "gemini, sonnet/claude, llama, qwen"
    raise ValueError(f"Unsupported llm provider '{llm_name}'. Supported: {supported}")
