from __future__ import annotations

import base64
import json
import logging
import threading
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Dict, List
from urllib import error as url_error
from urllib import request as url_request

import cv2

from gifdroid_llm.keyframes import Keyframe
from gifdroid_llm.llama_prereq import LlamaPrereqError, assert_llama_accessible


@dataclass(frozen=True)
class ProviderAction:
    screen_description: str
    action_type: str
    target: str
    details: str
    confidence: float


class ProviderError(RuntimeError):
    """Raised for provider-specific connectivity or inference failures."""


class BaseLLMProvider(ABC):
    """Common abstraction for open/closed model adapters."""

    def __init__(
        self,
        llm_name: str,
        llm_model: str,
        env: Dict[str, str],
        logger: logging.Logger,
    ) -> None:
        self.llm_name = llm_name
        self.llm_model = llm_model
        self.env = env
        self.logger = logger
        self.raw_llm_response: str | None = None

    @abstractmethod
    def infer_actions(self, keyframes: List[Keyframe]) -> List[ProviderAction]:
        """Infer action hypotheses from selected keyframes."""

    def validate_connection(self) -> None:
        """Optional provider preflight hook."""
        return None

    def _deterministic_fallback(self, keyframes: List[Keyframe], source: str) -> List[ProviderAction]:
        actions: List[ProviderAction] = []
        for idx, kf in enumerate(keyframes):
            if idx == 0:
                action_type = "launch_app"
                target = "app_entrypoint"
                details = f"{source}: initial frame likely app launch or resumed state"
                confidence = 0.88
            elif kf.motion_score >= 18:
                action_type = "tap"
                target = f"ui_element_step_{idx}"
                details = f"{source}: high visual transition suggests a click/tap action"
                confidence = 0.74
            elif kf.motion_score >= 9:
                action_type = "scroll"
                target = "scrollable_view"
                details = f"{source}: medium transition suggests scrolling/swiping"
                confidence = 0.66
            else:
                action_type = "wait"
                target = "current_screen"
                details = f"{source}: minimal transition indicates waiting or subtle input"
                confidence = 0.58

            desc = (
                f"Frame at {kf.timestamp_sec:.2f}s with motion_score={kf.motion_score:.2f}; "
                f"heuristic interpretation generated by {source}."
            )
            actions.append(
                ProviderAction(
                    screen_description=desc,
                    action_type=action_type,
                    target=target,
                    details=details,
                    confidence=confidence,
                )
            )
        return actions


class GeminiProvider(BaseLLMProvider):
    def validate_connection(self) -> None:
        self.logger.info(
            "Gemini preflight started | model=%s | validating API key and endpoint access",
            self.llm_model,
        )
        _ = self._call_gemini(
            prompt="Reply with exactly: OK",
            timeout_sec=30,
            request_kind="preflight",
        )
        self.logger.info("Gemini preflight successful | model=%s", self.llm_model)

    def infer_actions(self, keyframes: List[Keyframe]) -> List[ProviderAction]:
        if not keyframes:
            return []

        self.logger.info(
            "Sending Gemini inference request | model=%s | keyframes=%d",
            self.llm_model,
            len(keyframes),
        )
        prompt = self._build_action_prompt(keyframes)
        try:
            raw_text = self._call_gemini(
                prompt=prompt,
                timeout_sec=90,
                request_kind="action_inference",
            )
            parsed = self._parse_actions(raw_text, keyframes)
            if parsed:
                self.logger.info(
                    "Gemini inference parsed successfully | parsed_actions=%d",
                    len(parsed),
                )
                return parsed
            self.logger.warning(
                "Gemini response could not be parsed into actions; falling back to deterministic heuristic."
            )
        except ProviderError as exc:
            self.logger.warning(
                "Gemini inference request failed (%s); falling back to deterministic heuristic.",
                exc,
            )

        return self._deterministic_fallback(keyframes, source="gemini_fallback")

    def _build_action_prompt(self, keyframes: List[Keyframe]) -> str:
        keyframe_lines = [
            (
                f"- idx={idx + 1}, timestamp_sec={frame.timestamp_sec:.3f}, "
                f"motion_score={frame.motion_score:.3f}"
            )
            for idx, frame in enumerate(keyframes)
        ]
        joined = "\n".join(keyframe_lines)
        return (
            "You are inferring a mobile bug reproduction trace from frame metadata.\n"
            "Return ONLY valid JSON as an array, one object per keyframe, with keys:\n"
            "screen_description, action_type, target, details, confidence.\n"
            "confidence must be between 0 and 1.\n"
            "Keyframes:\n"
            f"{joined}\n"
        )

    def _call_gemini(self, prompt: str, timeout_sec: int, request_kind: str) -> str:
        api_key = self.env.get("GOOGLE_GENERATIVE_AI_API_KEY", "").strip()

        headers = {"Content-Type": "application/json"}
        endpoint_name = ""

        if api_key:
            auth_mode = "api_key"
            endpoint_name = "google_ai_studio"
            url = (
                "https://generativelanguage.googleapis.com/v1beta/models/"
                f"{self.llm_model}:generateContent?key={api_key}"
            )
        else:
            auth_mode = "adc_default"
            token, adc_project_id = self._build_default_adc_token()
            vertex_project_id = (
                str(self.env.get("GEMINI_VERTEX_PROJECT_ID", "")).strip() or adc_project_id
            )
            if not vertex_project_id:
                raise ProviderError(
                    "ADC did not provide a project_id and GEMINI_VERTEX_PROJECT_ID is not set."
                )
            headers["Authorization"] = f"Bearer {token}"
            location = str(self.env.get("GEMINI_VERTEX_LOCATION", "us-central1")).strip() or "us-central1"
            endpoint_name = "vertex_ai"
            url = (
                f"https://{location}-aiplatform.googleapis.com/v1/"
                f"projects/{vertex_project_id}/locations/{location}/publishers/google/models/"
                f"{self.llm_model}:generateContent"
            )
            self.logger.info(
                "Gemini ADC default credentials loaded | adc_project=%s | runtime_project=%s | token_present=%s",
                adc_project_id,
                vertex_project_id,
                bool(token),
            )
        self.logger.info(
            "Gemini auth route selected | route=%s | endpoint=%s",
            auth_mode,
            endpoint_name,
        )

        payload = {
            "contents": [{"role": "user", "parts": [{"text": prompt}]}],
            "generationConfig": {"temperature": 0.1},
        }
        payload_bytes = json.dumps(payload).encode("utf-8")
        req = url_request.Request(
            url=url,
            data=payload_bytes,
            headers=headers,
            method="POST",
        )

        self.logger.info(
            "Gemini API request sent | kind=%s | model=%s | auth=%s | endpoint=%s | waiting for response",
            request_kind,
            self.llm_model,
            auth_mode,
            endpoint_name,
        )
        start = time.perf_counter()
        try:
            with url_request.urlopen(req, timeout=timeout_sec) as response:
                response_text = response.read().decode("utf-8")
        except url_error.HTTPError as exc:
            err_body = exc.read().decode("utf-8", errors="replace")
            raise ProviderError(
                f"Gemini HTTP error {exc.code} during {request_kind}: {err_body[:300]}"
            ) from exc
        except url_error.URLError as exc:
            raise ProviderError(f"Gemini URL error during {request_kind}: {exc}") from exc
        except TimeoutError as exc:
            raise ProviderError(
                f"Gemini request timed out during {request_kind} after {timeout_sec}s"
            ) from exc

        elapsed = time.perf_counter() - start
        self.logger.info(
            "Gemini API response received | kind=%s | elapsed_sec=%.2f",
            request_kind,
            elapsed,
        )

        try:
            data = json.loads(response_text)
            return self._extract_text(data)
        except (json.JSONDecodeError, KeyError, TypeError) as exc:
            raise ProviderError(f"Invalid Gemini response format during {request_kind}") from exc

    def _build_default_adc_token(self) -> tuple[str, str | None]:
        try:
            import google.auth
            from google.auth.transport.requests import Request
        except ImportError as exc:
            raise ProviderError(
                "google-auth is required for ADC auth. "
                "Install dependencies from gifdroid_llm/requirements.txt"
            ) from exc

        try:
            creds, project_id = google.auth.default(
                scopes=["https://www.googleapis.com/auth/cloud-platform"]
            )
            creds.refresh(Request())
        except Exception as exc:
            raise ProviderError(
                "Failed to load Application Default Credentials via google.auth.default(). "
                "Set GOOGLE_APPLICATION_CREDENTIALS, run gcloud auth application-default login, "
                "or provide GOOGLE_GENERATIVE_AI_API_KEY."
            ) from exc

        token = getattr(creds, "token", None)
        if not token:
            raise ProviderError("ADC token refresh returned empty token")
        return token, project_id

    def _extract_text(self, response_data: Dict[str, object]) -> str:
        candidates = response_data.get("candidates")
        if not isinstance(candidates, list) or not candidates:
            raise ProviderError("Gemini response missing candidates")

        first = candidates[0]
        if not isinstance(first, dict):
            raise ProviderError("Gemini candidate payload has invalid structure")

        content = first.get("content")
        if not isinstance(content, dict):
            raise ProviderError("Gemini candidate missing content")

        parts = content.get("parts")
        if not isinstance(parts, list) or not parts:
            raise ProviderError("Gemini candidate missing parts")

        texts: List[str] = []
        for part in parts:
            if isinstance(part, dict):
                text = part.get("text")
                if isinstance(text, str) and text.strip():
                    texts.append(text.strip())

        if not texts:
            raise ProviderError("Gemini response contained no text parts")
        return "\n".join(texts)

    def _parse_actions(
        self,
        raw_text: str,
        keyframes: List[Keyframe],
    ) -> List[ProviderAction] | None:
        text = raw_text.strip()
        if "```" in text:
            chunks = text.split("```")
            for chunk in chunks:
                cleaned = chunk.strip()
                if cleaned.startswith("json"):
                    cleaned = cleaned[4:].strip()
                if cleaned.startswith("["):
                    text = cleaned
                    break
        if not text.startswith("["):
            return None

        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            return None
        if not isinstance(parsed, list):
            return None

        actions: List[ProviderAction] = []
        for idx, item in enumerate(parsed):
            if idx >= len(keyframes):
                break
            if not isinstance(item, dict):
                return None
            screen_description = str(item.get("screen_description", "")).strip()
            action_type = str(item.get("action_type", "")).strip()
            target = str(item.get("target", "")).strip()
            details = str(item.get("details", "")).strip()
            confidence_raw = item.get("confidence", 0.5)
            try:
                confidence = float(confidence_raw)
            except (TypeError, ValueError):
                confidence = 0.5

            if not action_type:
                return None
            actions.append(
                ProviderAction(
                    screen_description=screen_description
                    or f"Gemini-inferred state for keyframe {idx + 1}",
                    action_type=action_type,
                    target=target or f"ui_target_{idx + 1}",
                    details=details or "No additional details provided by Gemini.",
                    confidence=max(0.0, min(1.0, confidence)),
                )
            )

        if not actions:
            return None
        while len(actions) < len(keyframes):
            fallback = self._deterministic_fallback(
                [keyframes[len(actions)]], source="gemini_partial_fallback"
            )[0]
            actions.append(fallback)
        return actions


class SonnetProvider(BaseLLMProvider):
    def infer_actions(self, keyframes: List[Keyframe]) -> List[ProviderAction]:
        # TODO: Integrate Anthropic Claude/Sonnet image+text API invocation.
        self.logger.warning(
            "Sonnet provider running in stub mode (TODO API integration). model=%s",
            self.llm_model,
        )
        return self._deterministic_fallback(keyframes, source="sonnet_stub")


class LlamaProvider(BaseLLMProvider):
    def validate_connection(self) -> None:
        try:
            assert_llama_accessible(
                base_url=str(self.env.get("LLAMA_BASE_URL", "")),
                model=self.llm_model,
                api_key=str(self.env.get("LLAMA_API_KEY", "")),
                timeout_sec=30,
            )
        except LlamaPrereqError as exc:
            raise ProviderError(str(exc)) from exc

    def infer_actions(self, keyframes: List[Keyframe]) -> List[ProviderAction]:
        if not keyframes:
            return []

        self.logger.info(
            "Sending Llama inference request | model=%s | keyframes=%d",
            self.llm_model,
            len(keyframes),
        )
        prompt = self._build_action_prompt(keyframes)
        raw_timeout = str(self.env.get("LLAMA_TIMEOUT_SEC", "")).strip()
        timeout_sec: int | None = None
        if raw_timeout:
            try:
                parsed = int(raw_timeout)
                timeout_sec = parsed if parsed > 0 else None
            except ValueError:
                pass
        self.logger.info(
            "Llama inference timeout | timeout_sec=%s",
            timeout_sec if timeout_sec is not None else "unlimited",
        )
        try:
            raw_text = self._call_llama(
                prompt=prompt,
                keyframes=keyframes,
                timeout_sec=timeout_sec,
                request_kind="action_inference",
            )
            self.raw_llm_response = raw_text
            parsed = self._parse_actions(raw_text, keyframes)
            if parsed:
                self.logger.info(
                    "Llama inference parsed successfully | parsed_actions=%d",
                    len(parsed),
                )
                return parsed
            self.logger.warning(
                "Llama response could not be parsed into actions; falling back to deterministic heuristic."
            )
        except ProviderError as exc:
            self.logger.warning(
                "Llama inference request failed (%s); falling back to deterministic heuristic.",
                exc,
            )

        return self._deterministic_fallback(keyframes, source="llama_fallback")

    def _build_action_prompt(self, keyframes: List[Keyframe]) -> str:
        keyframe_lines = [
            (
                f"- idx={idx + 1}, timestamp_sec={frame.timestamp_sec:.3f}, "
                f"motion_score={frame.motion_score:.3f}"
            )
            for idx, frame in enumerate(keyframes)
        ]
        joined = "\n".join(keyframe_lines)
        return (
            "You are a mobile QA engineer analysing screenshots from an Android app recording.\n"
            "Each screenshot image is a keyframe extracted from the video at the listed timestamp.\n"
            "Your task: describe what is visible on each screen and what user action caused the transition.\n"
            "\n"
            "Rules:\n"
            "- Look at the actual screenshot image to write screen_description. Describe the visible UI: "
            "screen title, main content area, buttons, dialogs, lists — be specific.\n"
            "- action_type must be one of: launch, tap, type, swipe, scroll, wait, long_press, back, open_menu, select.\n"
            "- target must name the concrete UI element the user interacted with (e.g. 'Enable AdAway button', "
            "'Hosts sources list', 'OK dialog button'). Never use None, N/A, unknown, or null.\n"
            "- details must explain in one sentence why that action was taken or what changed.\n"
            "- confidence is a float 0-1 reflecting how certain you are from the visual evidence.\n"
            "- motion_score hints at transition magnitude (0=static, high=large visual change); use it as a "
            "secondary signal only — the screenshot is primary.\n"
            "- Return ONLY a valid JSON array, no markdown fences, no extra text.\n"
            "- The array must have EXACTLY one object per keyframe, in order.\n"
            "\n"
            "Example output format (2 keyframes):\n"
            '[\n'
            '  {"screen_description": "AdAway home screen showing Enable button and status disabled",'
            ' "action_type": "launch", "target": "app_entrypoint",'
            ' "details": "App launched and showing initial disabled state.", "confidence": 0.92},\n'
            '  {"screen_description": "Hosts sources list with three entries and a refresh icon in toolbar",'
            ' "action_type": "tap", "target": "Hosts sources menu item",'
            ' "details": "User opened hosts sources to review blocklist entries.", "confidence": 0.85}\n'
            ']\n'
            "\n"
            "Keyframes to analyse:\n"
            f"{joined}\n"
        )

    def _call_llama(
        self,
        prompt: str,
        keyframes: List[Keyframe] | None,
        timeout_sec: int | None,
        request_kind: str,
    ) -> str:
        base_url = str(self.env.get("LLAMA_BASE_URL", "")).strip()
        if not base_url:
            raise ProviderError("Missing LLAMA_BASE_URL for llama provider.")

        normalized_base = base_url.rstrip("/")
        if normalized_base.endswith("/v1/chat/completions"):
            url = normalized_base
        elif normalized_base.endswith("/v1"):
            url = f"{normalized_base}/chat/completions"
        else:
            url = f"{normalized_base}/v1/chat/completions"

        headers = {"Content-Type": "application/json"}
        api_key = str(self.env.get("LLAMA_API_KEY", "")).strip()
        if api_key:
            headers["Authorization"] = f"Bearer {api_key}"

        payload: Dict[str, Any] = {
            "model": self.llm_model,
            "temperature": 0.1,
            "stream": True,
        }
        if self._supports_vision() and keyframes:
            payload["messages"] = [
                {
                    "role": "user",
                    "content": self._build_multimodal_content(prompt, keyframes),
                }
            ]
        else:
            payload["messages"] = [{"role": "user", "content": prompt}]

        payload_bytes = json.dumps(payload).encode("utf-8")
        req = url_request.Request(
            url=url,
            data=payload_bytes,
            headers=headers,
            method="POST",
        )

        self.logger.info(
            "Llama API request sent | kind=%s | model=%s | endpoint=%s | waiting for response",
            request_kind,
            self.llm_model,
            url,
        )
        start = time.perf_counter()

        # Heartbeat: log every 2 min while waiting so the log shows the model is still working
        heartbeat_stop = threading.Event()
        def _heartbeat() -> None:
            interval = 120
            elapsed_hb = 0
            while not heartbeat_stop.wait(timeout=interval):
                elapsed_hb += interval
                self.logger.info(
                    "Llama still processing | kind=%s | elapsed_sec=%d | tokens_so_far=%d",
                    request_kind,
                    elapsed_hb,
                    len(accumulated_tokens),
                )
        accumulated_tokens: List[str] = []
        hb_thread = threading.Thread(target=_heartbeat, daemon=True)
        hb_thread.start()

        try:
            with url_request.urlopen(req, timeout=timeout_sec) as response:
                for raw_line in response:
                    line = raw_line.decode("utf-8").strip()
                    if not line:
                        continue
                    # Strip SSE "data: " prefix if present
                    if line.startswith("data:"):
                        line = line[len("data:"):].strip()
                    if line in ("[DONE]", ""):
                        continue
                    try:
                        chunk = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    delta = ""
                    choices = chunk.get("choices")
                    if isinstance(choices, list) and choices:
                        delta = str(choices[0].get("delta", {}).get("content") or "")
                    if delta:
                        accumulated_tokens.append(delta)
                        self.logger.debug("Llama token chunk | chars=%d | content=%r", len(delta), delta[:80])
        except url_error.HTTPError as exc:
            heartbeat_stop.set()
            err_body = exc.read().decode("utf-8", errors="replace")
            raise ProviderError(
                f"Llama HTTP error {exc.code} during {request_kind}: {err_body[:300]}"
            ) from exc
        except url_error.URLError as exc:
            heartbeat_stop.set()
            raise ProviderError(f"Llama URL error during {request_kind}: {exc}") from exc
        except TimeoutError as exc:
            heartbeat_stop.set()
            partial = "".join(accumulated_tokens)
            self.logger.warning(
                "Llama request timed out during %s after %ss | partial_chars=%d | partial_preview=%r",
                request_kind,
                timeout_sec,
                len(partial),
                partial[:200],
            )
            raise ProviderError(
                f"Llama request timed out during {request_kind} after {timeout_sec}s"
            ) from exc
        finally:
            heartbeat_stop.set()

        elapsed = time.perf_counter() - start
        full_text = "".join(accumulated_tokens)
        self.logger.info(
            "Llama API response complete | kind=%s | elapsed_sec=%.2f | total_chars=%d",
            request_kind,
            elapsed,
            len(full_text),
        )
        return full_text

    def _parse_actions(
        self,
        raw_text: str,
        keyframes: List[Keyframe],
    ) -> List[ProviderAction] | None:
        text = raw_text.strip()
        if "```" in text:
            chunks = text.split("```")
            for chunk in chunks:
                cleaned = chunk.strip()
                if cleaned.startswith("json"):
                    cleaned = cleaned[4:].strip()
                if cleaned.startswith("["):
                    text = cleaned
                    break
        if not text.startswith("["):
            bracket_idx = text.find("\n[")
            if bracket_idx != -1:
                text = text[bracket_idx:].strip()
            else:
                return None

        # Strip any trailing prose after the JSON array (e.g. "Note: ..." lines)
        bracket_end = text.rfind("]")
        if bracket_end != -1:
            text = text[: bracket_end + 1]

        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            return None
        if not isinstance(parsed, list):
            return None

        actions: List[ProviderAction] = []
        for idx, item in enumerate(parsed):
            if idx >= len(keyframes):
                break
            if not isinstance(item, dict):
                return None
            screen_description = str(item.get("screen_description", "")).strip()
            action_type = self._normalize_action_type(str(item.get("action_type", "")).strip())
            target = str(item.get("target", "")).strip()
            details = str(item.get("details", "")).strip()
            confidence_raw = item.get("confidence", 0.5)
            try:
                confidence = float(confidence_raw)
            except (TypeError, ValueError):
                confidence = 0.5

            if not action_type:
                return None
            if self._is_placeholder_text(screen_description):
                return None
            if self._is_placeholder_text(details):
                return None
            if self._is_placeholder_text(target) and action_type != "launch":
                return None
            actions.append(
                ProviderAction(
                    screen_description=screen_description
                    or f"Llama-inferred state for keyframe {idx + 1}",
                    action_type=action_type,
                    target=target or f"ui_target_{idx + 1}",
                    details=details or "No additional details provided by Llama.",
                    confidence=max(0.0, min(1.0, confidence)),
                )
            )

        if not actions:
            return None
        while len(actions) < len(keyframes):
            fallback = self._deterministic_fallback(
                [keyframes[len(actions)]], source="llama_partial_fallback"
            )[0]
            actions.append(fallback)
        return actions

    def _supports_vision(self) -> bool:
        model = self.llm_model.lower()
        return "vision" in model or "vl" in model

    def _build_multimodal_content(
        self,
        prompt: str,
        keyframes: List[Keyframe],
    ) -> List[Dict[str, Any]]:
        content: List[Dict[str, Any]] = [{"type": "text", "text": prompt}]
        for idx, frame in enumerate(keyframes, start=1):
            content.append(
                {
                    "type": "text",
                    "text": (
                        f"Screenshot for keyframe {idx} (idx={idx}, "
                        f"timestamp_sec={frame.timestamp_sec:.3f}, "
                        f"motion_score={frame.motion_score:.3f}). "
                        f"Describe exactly what you see on this Android screen:"
                    ),
                }
            )
            content.append(
                {
                    "type": "image_url",
                    "image_url": {"url": self._encode_keyframe_data_url(frame)},
                }
            )
        return content

    def _encode_keyframe_data_url(self, frame: Keyframe) -> str:
        image = frame.image_bgr
        h, w = image.shape[:2]
        max_dim = 768
        if max(h, w) > max_dim:
            scale = max_dim / float(max(h, w))
            image = cv2.resize(image, (int(w * scale), int(h * scale)), interpolation=cv2.INTER_AREA)

        ok, encoded = cv2.imencode(".jpg", image, [int(cv2.IMWRITE_JPEG_QUALITY), 80])
        if not ok:
            raise ProviderError("Failed to encode keyframe image for Llama vision request.")
        data_b64 = base64.b64encode(encoded.tobytes()).decode("ascii")
        return f"data:image/jpeg;base64,{data_b64}"

    def _normalize_action_type(self, action_type: str) -> str:
        lowered = action_type.strip().lower().replace(" ", "_")
        mapping = {
            "click": "tap",
            "press": "tap",
            "input": "type",
            "enter_text": "type",
            "scroll_down": "scroll",
            "swipe_up": "swipe",
            "swipe_down": "swipe",
            "app_launch": "launch",
            "launch_app": "launch",
        }
        normalized = mapping.get(lowered, lowered)
        allowed = {
            "launch",
            "tap",
            "type",
            "swipe",
            "scroll",
            "wait",
            "long_press",
            "back",
            "open_menu",
            "select",
        }
        if normalized not in allowed:
            return ""
        return normalized

    def _is_placeholder_text(self, value: str) -> bool:
        lowered = value.strip().lower()
        return lowered in {"", "none", "n/a", "na", "unknown", "null"}


class QwenProvider(BaseLLMProvider):
    def infer_actions(self, keyframes: List[Keyframe]) -> List[ProviderAction]:
        # TODO: Integrate Qwen endpoint (DashScope/OpenAI-compatible) API call.
        self.logger.warning(
            "Qwen provider running in stub mode (TODO API integration). model=%s",
            self.llm_model,
        )
        return self._deterministic_fallback(keyframes, source="qwen_stub")


def create_provider(
    llm_name: str,
    llm_model: str,
    env: Dict[str, str],
    logger: logging.Logger,
) -> BaseLLMProvider:
    provider_key = llm_name.lower()
    if provider_key == "gemini":
        return GeminiProvider(provider_key, llm_model, env, logger)
    if provider_key in {"sonnet", "claude"}:
        return SonnetProvider(provider_key, llm_model, env, logger)
    if provider_key == "llama":
        return LlamaProvider(provider_key, llm_model, env, logger)
    if provider_key == "qwen":
        return QwenProvider(provider_key, llm_model, env, logger)

    supported = "gemini, sonnet/claude, llama, qwen"
    raise ValueError(f"Unsupported llm provider '{llm_name}'. Supported: {supported}")
